zh-CN translation support.
vuejs/composition-api-rfc pull request #23
Opened 2020-04-21 05:49 UTC by ShenQingchuan

```
zh
├── api.md
├── dictionary.md
└── index.md

0 directories, 3 files
```
modified the `.vuepress/config.js` to support `locales`.

2020-04-22 16:05 UTC, Jinjiang reviewed
Will review by section. Here is some advice for `index.md`, from beginning to "Motivation" part.

Additionally, here is some [convention](https://github.com/vuejs/cn.vuejs.org/wiki) for all Vue translation work, which you could refer to.

All comments are just advice, please feel free to refer.

Thanks.

2020-04-22 16:05 UTC, Jinjiang commented on zh/index.md
> +观看 Vue Mastery 上的 [Vue 3 基础课程](https://www.vuemastery.com/courses/vue-3-essentials/why-the-composition-api/). 点击此链接下载 [Vue 3 代码笔记](https://www.vuemastery.com/vue-3-cheat-sheet/).
```suggestion
观看 Vue Mastery 上的 [Vue 3 基础课程](https://www.vuemastery.com/courses/vue-3-essentials/why-the-composition-api/). 点击此链接下载 [Vue 3 手册](https://www.vuemastery.com/vue-3-cheat-sheet/).
```

之前 cheat sheet 都译为了“手册“

2020-04-22 16:05 UTC, Jinjiang commented on zh/index.md
> +1. 随着功能的增长，复杂组件的代码变得越来越难以阅读和理解。这种情况在开发人员阅读他人编写的代码时尤为常见。根本原因是 Vue 现有的 API 强制通过「**选项**」组织代码，但是在某些情况下，通过逻辑关系组织代码更有意义。
```suggestion
1. 随着功能的增长，复杂组件的代码变得越来越难以阅读和理解。这种情况在开发人员阅读他人编写的代码时尤为常见。根本原因是 Vue 现有的 API 迫使我们通过选项组织代码，但是有的时候通过逻辑关系组织代码更有意义。
```

这里原文并没有加引号或加粗，建议仍保持一致。

2020-04-22 16:05 UTC, Jinjiang commented on zh/index.md
> +2. 目前缺少一种简洁且低成本的机制来提取和重用多个组件之间的逻辑。 (更多细节详见这里的描述： [逻辑抽象、提取与复用](#逻辑抽象、提取与复用))
```suggestion
2. 目前缺少一种简洁且低成本的机制来提取和重用多个组件之间的逻辑。 (详见 [逻辑抽象、提取与复用](#逻辑抽象、提取与复用))
```

2020-04-22 16:05 UTC, Jinjiang commented on zh/index.md
> +RFC 中 提出的 API 为用户在组织组件代码时提供了更大的灵活性。现在我们不需要总是通过「选项」来组织代码，而是可以将代码组织为处理特定功能的函数。这些 API 还使得在组件之间甚至组件外部提取和重用逻辑变得更加简单。
```suggestion
RFC 中提出的 API 为组件代码的组织提供了更大的灵活性。现在我们不需要总是通过选项来组织代码，而是可以将代码组织为处理特定功能的函数。这些 API 还使得在组件之间甚至组件之外逻辑的提取和重用变得更加简单。
```

2020-04-22 16:05 UTC, Jinjiang commented on zh/index.md
> +我们会在这一小节中 [设计细节](#设计细节) 为你展示我们想要达成的效果。
```suggestion
我们会在[设计细节](#设计细节)这一节展示达成的效果。
```
尝试简化描述，Btw 这一行应该和上一行在一起，否则实际渲染出来会多一个空格。

2020-04-22 16:05 UTC, Jinjiang commented on zh/index.md
> +另外一部分功能需求的声音来自一些大型项目的开发者，呼吁更好的 TypeScript 支持。Vue 当前的 API 在集成 TypeScript 时遇到了不小的麻烦，其主要原因是：我们实际上十分依赖一个简单的 `this` 上下文来提供各种数据、方法等属性，我们现在使用 `this` 的方式是比较玄学的。（比如说：我们访问某个组件的方法时是直接从 `this` 上取而不是在 `methods`上取
```suggestion
另一个来自大型项目开发者的常见需求是更好的 TypeScript 支持。Vue 当前的 API 在集成 TypeScript 时遇到了不小的麻烦，其主要原因是 Vue 依靠一个简单的 `this` 上下文来暴露 property，我们现在使用 `this` 的方式是比较黑魔法的。（比如 `methods` 选项下的函数的 `this` 是指向组件实例的，而不是这个 `methods` 对象）。
```

- 个人建议回避类似”玄学“这样的暗喻，以最大可能避免对任何群体有任何不敬
- 不确定”magic“译为”黑魔法“是否更妥当……

2020-04-22 16:05 UTC, Jinjiang commented on zh/index.md
> +换句话说，Vue 当前的各种 API 在设计时其实并没有基于类型推导的思想，这为我们之后想要适配 TypeScript 带来了很大挑战。
```suggestion
换句话说，Vue 现有的 API 在设计之初没有照顾到类型推导，这使适配 TypeScript 变得复杂。
```

2020-04-22 16:05 UTC, Jinjiang commented on zh/index.md
> +当前，大部分在 Vue 项目中应用 TypeScript 的开发者，都选择了官方提供的 `vue-class-component`，这个库使得 Vue 组件的写法变为一个 TypeScript 的类。 (而且运用了 Decorators 装饰器). 当我们在设计 3.0 时, 我们原本希望提供一个内建的 Class-API 来更好的解决「类型标注（typing）」相关的问题 [详见此已废弃 RF
```suggestion
当前，大部分使用 TypeScript 的 Vue 开发者都在通过 `vue-class-component` 这个库将组件撰写为 TypeScript class (借助 decorator)。我们在设计 3.0 时曾有[一个已废弃的 RFC](https://github.com/vuejs/rfcs/pull/17)，希望提供一个内建的 Class API 来更好的解决类型问题。然而当讨论并迭代其具体设计时，我们注意到，想通过 Class API 来解决类型问题，就必须依赖 decorator——一个在实现细节上存在许多未知数的非常不稳定的 stage 2 提案。基于它是有极大风险的。([关于 Class API 的类型相关问题请移步这里](#class-api-的类型问题))
```

2020-04-22 16:05 UTC, Jinjiang commented on zh/index.md
> +相比较过后，本 RFC 中提出的方案更多地是去利用原始的变量与函数，而恰恰它们在 TypeScript 是天然「**类型友好**」的，在使用我们现在提出的这种 API 写代码时，你会享受到完美的类型推导，并且也不用做太多额外的类型标注。
```suggestion
相比较过后，本 RFC 中提出的方案更多地利用了天然对类型友好的普通变量与函数。用该提案中的 API 撰写的代码会完美享用类型推导，并且也不用做太多额外的类型标注。
```

- plain -> 普通会不会更好？

2020-04-22 16:05 UTC, Jinjiang commented on zh/index.md
> +这也同样意味着：**你写出的 JavaScript 代码几乎就是 TypeScript 的代码**，所以即使是不想采用 TypeScript 的开发者也会从（例如 Visual Studio Code）IDE 给出的类型提示中受益。
```suggestion
这也同样意味着你写出的 JavaScript 代码几乎就是 TypeScript 的代码。即使是非 TypeScript 开发者也会因得到更好的 IDE 类型支持而获益。
```

2020-04-22 16:15 UTC, ShenQingchuan commented on zh/index.md
> +另外一部分功能需求的声音来自一些大型项目的开发者，呼吁更好的 TypeScript 支持。Vue 当前的 API 在集成 TypeScript 时遇到了不小的麻烦，其主要原因是：我们实际上十分依赖一个简单的 `this` 上下文来提供各种数据、方法等属性，我们现在使用 `this` 的方式是比较玄学的。（比如说：我们访问某个组件的方法时是直接从 `this` 上取而不是在 `methods`上取
确实，我个人在翻译这个词的时候甚至有考虑保留 `magic` 原文，因为这个词在大家的印象中好像就是一个 英文直出词，在汉语中我没有找到一个特别恰当的对应，当时觉得「玄」这个字可能凝练出了相应的内涵。

我赞成翻译为「黑魔法」。

2020-04-22 16:18 UTC, ShenQingchuan commented
感谢您为本次翻译提出的宝贵意见，能为 Vue Composition API 做翻译，对我来说是一件荣幸的事！这是我的第一次文档翻译历程，期望能够学习到更多！

2020-04-23 09:29 UTC, ShenQingchuan commented on zh/index.md
> +这也同样意味着：**你写出的 JavaScript 代码几乎就是 TypeScript 的代码**，所以即使是不想采用 TypeScript 的开发者也会从（例如 Visual Studio Code）IDE 给出的类型提示中受益。
> 这也同样意味着你写出的 JavaScript 代码几乎就是 TypeScript 的代码。即使是非 TypeScript 开发者也会 **因得** 到更好的 IDE 类型支持而获益。

typo: 这也同样意味着你写出的 JavaScript 代码几乎就是 TypeScript 的代码。即使是非 TypeScript 开发者也会 **因此得** 到更好的 IDE 类型支持而获益。

2020-04-23 09:33 UTC, ShenQingchuan commented on zh/index.md
> +另外一部分功能需求的声音来自一些大型项目的开发者，呼吁更好的 TypeScript 支持。Vue 当前的 API 在集成 TypeScript 时遇到了不小的麻烦，其主要原因是：我们实际上十分依赖一个简单的 `this` 上下文来提供各种数据、方法等属性，我们现在使用 `this` 的方式是比较玄学的。（比如说：我们访问某个组件的方法时是直接从 `this` 上取而不是在 `methods`上取
今天见到有对 `tricky` 这个单词翻译为 **_adj._ 微妙的**
我觉得在 “对某功能了解不太清晰，需要深入探究” 这一层意思上，似乎二者有共通处。

故献上参考词：「 ... 我们现在使用 `this` 对方式是比较微妙的 ... 」

2020-04-23 09:48 UTC, ShenQingchuan commented
Today (`2020 / 04 /23`) I've already resolved all the suggestions, but in order to avoid many useless, fragmented commits in this offical repo, I decided to `commit` them in one `push`.

今天 (`2020 / 04 /23`) 我已经将您所提出的所有建议全部做了修改，然而我之前已经做了一次提交，是关于上次翻译留下的一段缺漏。

因此为了避免碎片化的多次 `commit`，我想之后多次 review 检查校对完成后再统一提交。

2020-04-23 17:05 UTC, Jinjiang reviewed
Reviewed to the content before "Lifecycle Hooks" in `index.md`.

2020-04-23 17:05 UTC, Jinjiang commented on zh/index.md
> +为了不引入太多全新的概念，API 中提供的更多是 Vue 的核心功能。比如用独立的函数来创建和监听响应式的状态等...
```suggestion
为了不引入全新的概念，该提案中的 API 更像是暴露 Vue 的核心功能——比如用独立的函数来创建和监听响应式的状态等。
```

2020-04-23 17:05 UTC, Jinjiang commented on zh/index.md
> +在这里我们会介绍许多最基本的 API，它们可以被用于替换 2.x「Options API」当中的一些「组件内逻辑」
```suggestion
在这里我们会介绍一些最基本的 API，及其如何取代 2.x 的选项表述组件内逻辑。
```

2020-04-23 17:05 UTC, Jinjiang commented on zh/index.md
> +**请注意：** 这一小节中我们主要是介绍这些 API 的基本思想所以我们不会太多深入展开其细节。更多的使用细节请移步 [API 参考](./api) 章节。
```suggestion
请注意，本节主要会介绍这些 API 的基本思路，所以不会展开至其完整的细节。完整的 API 规范请移步 [API 参考](./api)章节。
```

2020-04-23 17:05 UTC, Jinjiang commented on zh/index.md
> +#### 响应式状态 与 被动响应
```suggestion
#### 响应式状态与副作用
```

2020-04-23 17:05 UTC, Jinjiang commented on zh/index.md
> +`reactive` 几乎等价于我们现有 2.x 中的 `Vue.observable()` API，重命名成这样是为了与 RxJS 中的 `observables` 区别开来。在这里，返回的 `state` 是一个响应式的对象，关于 “响应式” 的概念相信所有的 Vue 使用者都比较熟悉了。
```suggestion
`reactive` 几乎等价于 2.x 中现有的 `Vue.observable()` API，且为了避免与 RxJS 中的 observable 混淆而做了重命名。这里返回的 `state` 是一个所有 Vue 用户都应该熟悉的响应式对象。
```

2020-04-23 17:05 UTC, Jinjiang commented on zh/index.md
> +我们可以将这个基本的示例的使用扩展到界面内容渲染上，因为有了依赖收集的机制，当响应式的状态发生改变时，视图会自动地进行更新。在 DOM 当中渲染些什么被视为一种「**被动响应 effect**」：程序在执行过程中修改了这个变量，同时将其状态的改变所引发的副作用反映出来（_这里指的就是 DOM 内容的变更_）。
```suggestion
在 Vue 中，响应式状态的基本用例就是在渲染时使用它。因为有了依赖追踪，视图会在响应式状态发生改变时自动更新。在 DOM 当中渲染内容会被视为一种”副作用“：程序会在外部修改其本身 (也就是这个 DOM) 的状态。我们可以使用 `watchEffect` API 应用基于响应式状态的副作用，并_自动_进行重应用。
```

2020-04-23 17:05 UTC, Jinjiang commented on zh/index.md
> +对此我们可以使用 `watchEffect` 这个 API：
```suggestion
```

2020-04-23 17:05 UTC, Jinjiang commented on zh/index.md
> +`watchEffect` 期望接收一个函数，这个函数定义之中，应该描述了被动响应所期望的结果。**刚开始时它将会立即执行这个函数**，因而可以对这个过程中用到的响应式状态进行「**追踪监听 track**」，将其作为这个被动响应的「**依赖 dependency**」。
```suggestion
`watchEffect` 应该接收一个应用预期副作用 (这里即设置 `innerHTML`) 的函数。它会立即执行该函数，并将该执行过程中用到的所有响应式状态的 property 作为依赖进行追踪。
```

2020-04-23 17:05 UTC, Jinjiang commented on zh/index.md
> +也就是在示例中，`state.count` 在首次执行后，会被追踪，成为一个依赖。当 `state.count` 未来发生变化时，里面这个函数又会被重新执行。
```suggestion
这里的 `state.count` 会在首次执行后作为依赖被追踪。当 `state.count` 未来发生变更时，里面这个函数又会被重新执行。
```

2020-04-23 17:05 UTC, Jinjiang commented on zh/index.md
> +这正是 Vue 目前整个响应式系统的精髓所在了！在 2.x 中，当你从 `data()` 函数中返回一个对象，内部实质上通过调用 `reactive()` 使其变为响应式。而 `template` 模板会被编译为「渲染函数（render function）」（你可以把它想成一种更复杂的 `innerHTML` 变更方式），故而可以将响应式状态应用其中。
```suggestion
这正是 Vue 响应式系统的精髓所在了！当你在组件中从 `data()` 返回一个对象，内部实质上通过调用 `reactive()` 使其变为响应式。而模板会被编译为渲染函数 (可被视为一种更高效的 `innerHTML`)，故可以使用这些响应式的 property。
```

Btw 3.0 同样是支持 `data()` 的

2020-04-23 17:05 UTC, Jinjiang commented on zh/index.md
> +> `watchEffect` 方法和 2.x 中的 `watch` 选项比较类似，但是它略有不同，参数中并不要求分开书写 _被监听的数据对象_ 和 _被动响应的回调函数_。不过 Composition API 同样提供了一个 `watch` 方法，参数及用法完全与 2.x 的选项表现一致。
```suggestion
> `watchEffect` 方法和 2.x 中的 `watch` 选项比较类似，但参数中并不要求将被监听的数据源和副作用回调函数分开。Composition API 同样提供了一个 `watch` 函数，行为与 2.x 选项完全一致。
```

2020-04-23 17:05 UTC, Jinjiang commented on zh/index.md
> +但是在 Vue 的模板系统当中，我们当然不需要完全按照原生 JavaScript 一样，去手动的去调整 `innerHTML` 或是去挂载事件监听。我们将例子中渲染相关的逻辑简化为一个假设的 `renderTemplate` 方法即可，这样我们就可以更多关注响应式方面的内容了：
```suggestion
但是在 Vue 的模板系统当中，我们不需要纠结用 `innerHTML` 还是手动挂载事件监听器。让我们将例子简化为一个假设的 `renderTemplate` 方法，以专注在响应性这方面：
```

2020-04-23 17:05 UTC, Jinjiang commented on zh/index.md
> +#### 计算属性 与 响应式值引用
```suggestion
#### 计算属性与 Ref
```

个人建议 ref 这个词不翻译了，直接用英文，以避免误会和歧义

2020-04-23 17:05 UTC, Jinjiang commented on zh/index.md
> +有时候，我们会需要一个 _依赖于其他状态的_ 状态，在 Vue 中我们将它称为 **计算属性**，我们可以使用 `computed` 方法直接创建一个计算属性。
```suggestion
有时候，我们会需要一个依赖于其他状态的状态，在 Vue 中这是通过_计算属性_来处理的。我们可以使用 `computed` API 直接创建一个计算属性：
```

2020-04-23 17:05 UTC, Jinjiang commented on zh/index.md
> +这个 `computed` 返回了什么? 我们可以猜想一下 `computed` 内部是如何实现的，你可能会想出下面这样的方案:
```suggestion
这个 `computed` 返回了什么? 如果猜一下 `computed` 内部是如何实现的，我们可能会想出下面这样的方案:
```

2020-04-23 17:05 UTC, Jinjiang commented on zh/index.md
> +但实际上并不是这样的：如果 `value` 只是一个 JavaScript 中的基础值类型，例如 `number` 类型，当被返回时，它与这个 computed 句柄函数 `getter` 之间的关系就丢失了！
```suggestion
但我们知道它不会正常工作：如果 `value` 是一个例如 `number` 的基础类型，那么当被返回时，它与这个 `computed` 内部逻辑之间的关系就丢失了！
```

2020-04-23 17:05 UTC, Jinjiang commented on zh/index.md
> +这是由于 JavaScript 中基础类型是 **值传递** 而非 **引用传递**。
这里不应该折行

```suggestion
这是由于 JavaScript 中基础类型是值传递而非引用传递。
```

2020-04-23 17:05 UTC, Jinjiang commented on zh/index.md
> +在 “将基础类型的值，赋给某个对象作为其属性” 时也会出现同样的问题。我们不想让某个响应式的值 _在其被赋值成为一个属性时_、_或在函数中被返回时_ 丢失了其响应性。为了确保我们可以一直读取到最新的计算结果，我们需要将这个值上包裹成一个对象并返回它。
```suggestion
在把值作为 property 赋值给某个对象时也会出现同样的问题。一个响应式的值一旦作为 property 被赋值或从一个函数返回，而失去了响应性之后，也就失去了用途。为了确保始终可以读取到最新的计算结果，我们需要将这个值上包裹到一个对象中再返回。
```

2020-04-23 17:05 UTC, Jinjiang commented on zh/index.md
> +另外你必须知道的是：我们同样需要 **劫持** 对这个对象 `.value` 属性的 读/写 操作，来实现依赖收集与被动响应的更新。（为了缩减篇幅我们没有过多展示内部实现的原理）
```suggestion
另外我们同样需要拦截对这个对象 `.value` property 的读/写操作，来实现依赖收集与更新通知 (为了简化我们忽略这里的代码实现)。
```

2020-04-23 17:05 UTC, Jinjiang commented on zh/index.md
> +现在我们可以通过引用来传递计算属性值了！也不需要担心其响应式特性会丢失。当然代价就是：为了获取此值，我们每次都需要写 `.value`。
```suggestion
现在我们可以通过引用来传递计算属性值，也不需要担心其响应式特性会丢失了。当然代价就是：为了获取最新的值，我们每次都需要写 `.value`。
```

2020-04-23 17:05 UTC, Jinjiang commented on zh/index.md
> +**在这里 `double` 是一个对象，我们管它叫 "ref", 它作为它内部值的一个响应式引用。**
```suggestion
**在这里 `double` 是一个对象，我们管它叫“ref”, 用来作为一个响应性引用保留内部的值。**
```

2020-04-23 17:05 UTC, Jinjiang commented on zh/index.md
> +> 你可能会担心说：“诶！Vue 本身不是已经有 "refs" 的概念了么？”
```suggestion
> 你可能会担心 Vue 本身已经有“ref”的概念了，”
```

未翻译的所有复数词汇都转为单数

2020-04-23 17:05 UTC, Jinjiang commented on zh/index.md
> +> 原来的 `ref` 只是为了获取 DOM 元素或组建实例的「 template refs 模板引用」，更多详见这里的 [API 参考](./api.html#template-refs)，查看新的 refs 系统是如何同时兼容 _逻辑引用值_ 与 _模板引用_ 的。
这里是没有必要的折行

```suggestion
> 但只是为了在模板中获取 DOM 元素或组件实例 (“模板引用”)。可以来[这里](./api.html#template-refs)查看新的 ref 系统如何同时用于逻辑状态和模板引用。
```

2020-04-23 17:05 UTC, Jinjiang commented on zh/index.md
> +在 `computed` 之外，我们同样提供了一个 API 来直接创建一个「**响应式值引用 ref**」：
```suggestion
除了计算属性的 ref，我们还可以使用 `ref` API 直接创建一个可变更的普通的 ref：
```

2020-04-23 17:05 UTC, Jinjiang commented on zh/index.md
> +#### Ref 的自动解套
```suggestion
#### 解套 Ref
```

2020-04-23 17:05 UTC, Jinjiang commented on zh/index.md
> +我们可以在 `setup` 中将 `ref` 值暴露给模板渲染，在渲染过程中，Vue 会特别地为这些响应式值引用解套，上下文会直接使用其内部的值，也就是说你在写模板用到这个 `ref` 值时，不用再特意写 `.value` 了。
```suggestion
我们可以在 `setup` 中将 `ref` 值暴露给模板渲染，在渲染过程中，Vue 会特别地为这些响应式值引用解套，上下文会直接使用其内部的值，也就是说你在写模板用到这个 `ref` 值时，不用再特意写 `.value` 了。
我们可以在渲染的上下文中暴露一个 ref 作为其 property。Vue 内部的渲染上下文在遇到 ref 时会对其特别对待，即直接暴露其内部的值，也就是说在模板中你可以把 `{{ count.value }}` 直接写为 `{{ count }}` 。
```

2020-04-23 17:05 UTC, Jinjiang commented on zh/index.md
> +除此之外，当一个 `ref` 值嵌套于响应式对象之中时，访问时会自动解套:
```suggestion
除此之外，当一个 ref 嵌套于响应式对象之中时，会在访问时自动解套:
```

2020-04-23 17:05 UTC, Jinjiang commented on zh/index.md
> +// 无需再使用 `state.double.value` 访问其值
```suggestion
// 无需再使用 `state.double.value`
```

2020-04-23 17:05 UTC, Jinjiang commented on zh/index.md
> +到目前为止，我们的代码已经提供了一个可以根据用户输入进行更新的 UI ，但是代码只运行一次，无法重用。如果我们想重用其逻辑，那么不如重构成一个函数:
```suggestion
到目前为止，我们的代码已经提供了一个可以根据用户输入进行更新的 UI ，但是代码只运行了一次，无法再重用。如果我们想重用其逻辑，那么不如重构成一个函数:
```

2020-04-23 17:05 UTC, Jinjiang commented on zh/index.md
> +现在，如果我们把调用 `setup()`、创建 `computed` 计算属性 与模板渲染的逻辑组合在一起，其实就正是用它们来定义了一个 Vue 组件:
```suggestion
现在如果我们把调用 `setup()`、创建侦听器和渲染模板的逻辑组合在一起交给框架，我们就可以仅通过 `setup()` 函数和模板定义一个组件:
```

2020-04-23 17:05 UTC, Jinjiang commented on zh/index.md
> +看！这不就变成我们熟悉的「**单文件组件**」了么，只是逻辑部分 (`<script>`块) 格式表现得稍有不同，模板语法与原先保持一致（另外省略了 `<style>`）。
```suggestion
这就是我们熟悉的单文件组件格式，只是逻辑的部分 (`<script>`) 格式表现稍有不同。模板语法与原先保持一致。`<style>` 在这里被忽略了，但它工作起来同样与原先一直。
```

2020-04-23 17:06 UTC, Jinjiang commented
> 因此为了避免碎片化的多次 commit，我想之后多次 review 检查校对完成后再统一提交。

Hi，您其实可以及时 commit + push，不必介意 commit 过多，我们在最终 merge 的时候会做妥善处理。

2020-04-24 12:48 UTC, ShenQingchuan commented
> Hi，您其实可以及时 commit + push，不必介意 commit 过多，我们在最终 merge 的时候会做妥善处理。

Thanks for your suggestions, and I've already resolved all the review results in the latest commit. ( be almost the same as given suggestions. )

好的，我已经将 'Life Hooks' 之前的所有您审阅过的结果修改完成，烦请您再次审阅。（绝大部分与您给出的参考保持了一致。）

2020-04-24 17:31 UTC, Jinjiang reviewed
Reviewed the content before "Logic Extraction and Reuse".
Thanks.

2020-04-24 17:31 UTC, Jinjiang commented on zh/index.md
> +#### 解套 Ref
```suggestion
#### 解开 Ref
```

想到一个觉得更好的译法“解开”，下同。

2020-04-24 17:31 UTC, Jinjiang commented on zh/index.md
> +到此我们已经覆盖到了一个组件的状态的所有情况，响应式状态、计算属性和处理用户输入时的状态变化。但是一个组件本身可能还有其他的被动响应：例如打印信息到控制台、发送 AJAX 请求或是在全局 `window` 对象上设置事件监听器等等... 这些被动响应大多会发生在如下这些时间节点上：
```suggestion
到此我们已经覆盖了组件的纯状态层面：响应式状态、计算属性和用户输入时的状态变更。但是一个组件可能还会产生其它副作用——例如在控制台打印信息、发送 AJAX 请求或在全局 `window` 对象上设置事件监听器。这些副作用大多会发生在如下时间节点上：
```

side effect -> 副作用。下同。

2020-04-24 17:31 UTC, Jinjiang commented on zh/index.md
> +我们已经知道可以使用 `watchEffect` 和 `watch` API 来提供状态变化时的被动响应。为了表现出在一些生命周期时的被动响应，
```suggestion
我们知道在状态变化时可以使用 `watchEffect` 和 `watch` API 应用副作用。而为了在生命周期钩子中产生副作用，
```

去掉不必要的折行以避免渲染时出现空格，下同

2020-04-24 17:31 UTC, Jinjiang commented on zh/index.md
> +我们定义来一些形似 `onXXX` 的 API，与我们 2.x 现有的生命周期选项对应。
```suggestion
我们可以使用特有的 `onXXX` 的 API (对应现有的生命周期选项)。
```

2020-04-24 17:31 UTC, Jinjiang commented on zh/index.md
> +生命周期钩子表现为一种注册的方法，只在 `setup` 中使用。它会通过一个内部的全局状态自动找到调用此 `setup` 钩子方法的组件，这样设计是为了减少将逻辑提取到外部函数时的冲突。
```suggestion
这些生命周期注册方法只能用在 `setup` 钩子中。它会通过内部的全局状态自动找到调用此 `setup` 钩子的实例。这是一个有意的设计，为了减少将逻辑提取到外部函数时的冲突。
```

2020-04-24 17:31 UTC, Jinjiang commented on zh/index.md
> +> 关于这些 API 的更多细节可以在 [API 参考](./api)页面中找到。但是在深入挖掘使用细节之前，我们建议你先将下面介绍核心思想的小节看完。
```suggestion
> 关于这些 API 的更多细节可以在 [API 参考](./api)页面中找到。但是在深入挖掘设计细节之前，我们建议你先将接下来的章节看完。
```

2020-04-24 17:31 UTC, Jinjiang commented on zh/index.md
> +### 代码组织与管理
```suggestion
### 代码组织
```

2020-04-24 17:31 UTC, Jinjiang commented on zh/index.md
> +此时我们已经将原来 Options API 中的逻辑全部过继到了新的 API 中，但是这么做的目的是什么？用选项来定义组件难道不比把所有东西揉在一个大大的函数里更有条理、更具组织性么？
```suggestion
此时我们已经将组件的 API 复制成了一些被导入的函数，但是这么做的目的是什么？用选项来定义组件看上去比用一个混入所有东西的大函数更具组织性！
```

2020-04-24 17:31 UTC, Jinjiang commented on zh/index.md
> +有这样的第一印象是可以理解的。但是正如在 _动机与目的_ 部分所提到的，我们相信组合式的 API 实际上能够为你的代码带来更好组织结构，尤其是在复杂的组件中，下面我们将解释为什么。
```suggestion
这种第一印象可以理解。但正如动机与目的章节提到的，我们相信组合式的 API 实际上能够带来_更_有组织的代码，尤其是在复杂的组件中。下面我们将解释为什么。
```

2020-04-24 17:31 UTC, Jinjiang commented on zh/index.md
> +#### 到底什么才是 "组织较好的代码"
```suggestion
#### 什么是“有组织的代码”？
```

2020-04-24 17:31 UTC, Jinjiang commented on zh/index.md
> +让我们先暂退一步，考虑一下这个概念的真正内涵。最后我们的目标无外乎是 “让代码更具可读性、更容易被理解”，那么怎么才叫 “理解” 了代码呢？难道光是知道了它定义了哪些选项就算了解了一个组件本身么？你是否有接手过他人开发过的一个庞大组件？比如 [你看看这个](https://github.com/vuejs/vue-cli/blob/a09407dd5b9f18ace7501ddb603b95e3
```suggestion
让我们先暂退一步，考虑一下这个概念的真正内涵。有组织的代码的最终目标应该是让代码更可读、更容易被理解。那么怎么才叫“理解”代码呢？我们可以仅仅因为知道了它所包含的选项就算了解了一个组件么？你是否有接手过他人的庞大组件 (比如[这个](https://github.com/vuejs/vue-cli/blob/a09407dd5b9f18ace7501ddb603b95e31d6d93c0/packages/@vue/cli-ui/src/components/folder/FolderExplorer.vue#L198-L404) 并觉得头大？
```

2020-04-24 17:31 UTC, Jinjiang commented on zh/index.md
> +那么想一想，我们怎么才能让后来的开发者弄懂上面链接里这样一个大型组件的内在逻辑？你可能大致会开始分析道：“这个组件是在处理 X、Y 与 Z” 而不会说 “这个组件有这些那些个数据属性（`data`）、这些那些个计算属性（`computed`）和这些那些个方法（`methods`）”。
```suggestion
想想看我们该如何跟别的开发者同步理解上面链接里那样的一个大型组件。你大概会从“这个组件在处理 X、Y 与 Z”开始，而是“这个组件有这些数据 property、这些计算属性和这些方法”。
```

2020-04-24 17:31 UTC, Jinjiang commented on zh/index.md
> +当要去理解一个组件时，我们更加关心的是 “这个组件是要干什么”（也就是说：代码对应的的需求、所展现的意图）而不是 “这个组件用到了什么选项”。但我们的 Options API 实际上就是后者。
```suggestion
当要去理解一个组件时，我们更加关心的是“这个组件是要干什么” (即代码背后的意图) 而不是“这个组件用到了什么选项”。基于选项的 API 撰写出来的代码自然采用了后者的表述方式，而对前者的表述并不好。
```

2020-04-24 17:31 UTC, Jinjiang commented on zh/index.md
> +我们不妨将组件处理的 `X、Y 和 Z` 定义为此组件的「**逻辑关注**」，可读性的问题基本不会存在于小的、单一用途的组件中，因为那样的组件，整个都在处理单个逻辑关注点，然而，这个问题在复杂的用例中会变得突出。以 [Vue CLI UI 文件浏览器](https://github.com/vuejs/vue-cli/blob/a09407dd5b9f18ace7501ddb603b95e31d
```suggestion
我们不妨将组件处理的“X、Y 和 Z”定义为**逻辑关注点**。可读性的问题基本不会存在于小的、单一用途的组件中，因为整个组件都在处理同一个逻辑关注点。然而这个问题在复杂的用例中会变得突出。以 [Vue CLI UI 文件浏览器](https://github.com/vuejs/vue-cli/blob/a09407dd5b9f18ace7501ddb603b95e31d6d93c0/packages/@vue/cli-ui/src/components/folder/FolderExplorer.vue#L198-L404)为例，这个组件有非常多的逻辑关注点：
```

2020-04-24 17:31 UTC, Jinjiang commented on zh/index.md
> +#### 逻辑关注 vs. 选项类型
```suggestion
#### 逻辑关注点 vs. 选项类型
```

2020-04-24 17:31 UTC, Jinjiang commented on zh/index.md
> +- 处理文件夹的操作（打开、关闭、刷新或是其他...）
```suggestion
- 处理文件夹导航（打开、关闭、刷新...）
```

2020-04-24 17:31 UTC, Jinjiang commented on zh/index.md
> +- 处理「新建文件夹」的操作
```suggestion
- 处理新文件夹的创建
```

2020-04-24 17:31 UTC, Jinjiang commented on zh/index.md
> +- 控制「收藏文件夹」展开与否
```suggestion
- 是否只展示收藏文件夹
```

2020-04-24 17:31 UTC, Jinjiang commented on zh/index.md
> +- 控制「隐藏文件夹」展开与否
```suggestion
- 是否只展示隐藏文件夹
```

2020-04-24 17:31 UTC, Jinjiang commented on zh/index.md
> +- 对「文件夹路径变化」作出响应
```suggestion
- 处理当前工作目录的变化
```

2020-04-24 17:31 UTC, Jinjiang commented on zh/index.md
> +相对应的，你能仅仅通过基于选项的代码来梳理出各个逻辑关注点么？显然是十分困难的，因为最后我们会发现到与各个逻辑关注点相关的代码是分散在各处的。
```suggestion
你能通过阅读基于选项的代码直接梳理出各个逻辑关注点么？显然是十分困难的。你会发现到与各个逻辑关注点相关的代码是分散在各处的。
```

2020-04-24 17:31 UTC, Jinjiang commented on zh/index.md
> +例如：「创建新文件夹」的功能使用到了 [两个数据属性](https://github.com/vuejs/vue-cli/blob/a09407dd5b9f18ace7501ddb603b95e31d6d93c0/packages/@vue/cli-ui/src/components/folder/FolderExplorer.vue#L221-L222)、[一个计算属性](https://gi
```suggestion
例如“创建新文件夹”的功能使用到了[两个数据 property](https://github.com/vuejs/vue-cli/blob/a09407dd5b9f18ace7501ddb603b95e31d6d93c0/packages/@vue/cli-ui/src/components/folder/FolderExplorer.vue#L221-L222)、[一个计算属性](https://github.com/vuejs/vue-cli/blob/a09407dd5b9f18ace7501ddb603b95e31d6d93c0/packages/@vue/cli-ui/src/components/folder/FolderExplorer.vue#L240)和[一个方法](https://github.com/vuejs/vue-cli/blob/a09407dd5b9f18ace7501ddb603b95e31d6d93c0/packages/@vue/cli-ui/src/components/folder/FolderExplorer.vue#L387)，而方法的定义在距离数据 property 约一百多行的位置。
```

2020-04-24 17:31 UTC, Jinjiang commented on zh/index.md
> +如果我们对这些逻辑问题进行染色，我们会注意到它们在用组件选项表示时是多么分散:
```suggestion
如果我们对这些逻辑关注点进行染色，我们会注意到它们在用组件选项表示时是多么分散:
```

2020-04-24 17:31 UTC, Jinjiang commented on zh/index.md
> +正是这种碎片化使得理解和维护一个复杂的组件变得非常困难。强制的选项分离掩盖了潜在的逻辑问题。此外，在处理单个逻辑关注点时，我们必须不断地 “跳转” 选项的代码块，以找到与该关注点相关的部分。
```suggestion
正是这种碎片化使得理解和维护一个复杂的组件变得非常困难。选项的强行分离为背后的逻辑关注点设置了障碍。此外，在处理单个逻辑关注点时，我们必须不断地在选项代码块之间“跳转”，以找到与该关注点相关的部分。
```

2020-04-24 17:31 UTC, Jinjiang commented on zh/index.md
> +> **注意:** 原始代码可能在某些地方有些改动，但是我们展示了在撰写本文时的最新提交，没有进行任何修改，目的就是为了提供了一个我们自己编写的、实际生产代码的示例。
```suggestion
> **注意：**原始代码可能在某些地方有些改动，但是我们展示了在撰写本文时的最新提交，没有进行任何修改，目的就是为了提供了一个我们自己编写生产环境代码的真实示例。
```

2020-04-24 17:31 UTC, Jinjiang commented on zh/index.md
> +如果我们能够将与相同逻辑关注点对应的代码并列组合，那就再好不过了。这正是组合式 API 所能做到的，“创建新文件夹”功能可以这样写:
```suggestion
如果我们能够将相同逻辑关注点的代码并列在一起，那就再好不过了。这正是组合式 API 所能做到的，“创建新文件夹”功能可以这样写：
```

标点符号的全角半角格式建议保持统一，下同。

2020-04-24 17:31 UTC, Jinjiang commented on zh/index.md
> +  // 原来的数据属性改成这样写：
```suggestion
  // 原来的数据 property
```

2020-04-24 17:31 UTC, Jinjiang commented on zh/index.md
> +  // 原来的计算属性改成这样写：
```suggestion
  // 原来的计算属性
```

2020-04-24 17:31 UTC, Jinjiang commented on zh/index.md
> +  // 原来的一个方法改成这样写：
```suggestion
  // 原来的一个方法
```

2020-04-24 17:31 UTC, Jinjiang commented on zh/index.md
> +请注意，与「创建新文件夹」功能相关的所有逻辑现在都被合并并封装在一个函数中。由于其读起来具有描述性的名称，该函数的代码在某种程度上也是自文档化的、更易读的。这就是我们所称的：**组合逻辑函数**。建议使用 `use` 作为函数名的开头，以表示它是一个组合逻辑函数。
```suggestion
请注意，与创建新文件夹功能相关的所有逻辑现在都被合并并封装在了一个函数中。由于具有描述性的名称，该函数也是某种自文档。我们建议使用 `use` 作为函数名的开头，以表示它是一个组合函数。
```

2020-04-24 17:31 UTC, Jinjiang commented on zh/index.md
> +将此模式用于组件中所有的逻辑关注点，代码中各个部分间将更好地解耦和重组，来看看下图的对比吧:
```suggestion
此模式可用于该组件的所有其它逻辑关注点，最终成为一些良好解耦的函数:
```

2020-04-24 17:31 UTC, Jinjiang commented on zh/index.md
> +> 这个比较不包括 import 语句和 setup()函数。使用复合 API 重新实现的完整组件可以在 [这里](https://gist.github.com/yyx990803/8854f8f6a97631576c14b63c8acd8f2e) 找到。
```suggestion
> 这个比较不包括 import 语句和 `setup()` 函数。使用复合 API 重新实现的完整组件可以在[这里](https://gist.github.com/yyx990803/8854f8f6a97631576c14b63c8acd8f2e)找到。
```

2020-04-24 17:31 UTC, Jinjiang commented on zh/index.md
> +每个逻辑关注点的代码现在都被配置在一个组合逻辑函数中。这大大减少了在处理大型组件时不断 “跳转” 的需要。同时这一整个功能所对应的函数也可以在编辑器中折叠，使组件更容易浏览:
```suggestion
每个逻辑关注点的代码现在都被组合进了一个组合函数。这大大减少了在处理大型组件时不断“跳转”的需要。同时组合函数也可以在编辑器中折叠起来，使组件更容易浏览:
```

2020-04-24 17:31 UTC, Jinjiang commented on zh/index.md
> +`setup()` 函数现在只是简单地作为所有「组合逻辑函数」的调用入口。
```suggestion
`setup()` 函数现在只是简单地作为调用所有组合函数的入口：
```

2020-04-24 17:31 UTC, Jinjiang commented on zh/index.md
> +    // （从）其他工具函数（解构一些方法）
```suggestion
    // 实用工具
```

2020-04-24 17:31 UTC, Jinjiang commented on zh/index.md
> +当然，使用 Options API 时我们完全不会这么写代码。但是请注意，`setup` 函数读起来就已经几乎是对「组件正在尝试做什么」的口头描述了 —— 这是基于选项的版本中完全没有的信息。您还可以根据传递的参数清楚地看到复合函数之间的依赖关系。最后，`return` 语句用作检查模板中暴露的内容的单一出口。
```suggestion
当然，使用选项 API 时我们不会这么写代码。但是请注意 `setup` 函数读起来几乎像是在口述这个组件尝试做什么——这是基于选项的版本完全丢掉的信息。你还可以根据传递的参数清楚地看到组合函数之间的依赖关系。最后的 return 语句作为单一出口确认暴露给模板的内容。
```

“您”和“你”的使用建议保持一致
“组合函数”和“复合函数”的使用建议保持一致

2020-04-24 17:31 UTC, Jinjiang commented on zh/index.md
> +同样的功能、两套组件定义呈现出对内在逻辑的不同的表达方式。基于选项的 API 促使我们通过「_选项类型_」来管理代码，而组合式 API 是我们拥有了基于「_逻辑关注点_」管理代码的新套路。
```suggestion
同样的功能、两套组件定义呈现出对内在逻辑的不同的表达方式。基于选项的 API 促使我们通过_选项类型_组织代码，而组合式 API 让我们可以基于_逻辑关注点_组织代码。
```

2020-04-25 00:26 UTC, ShenQingchuan commented on zh/index.md
> +让我们先暂退一步，考虑一下这个概念的真正内涵。最后我们的目标无外乎是 “让代码更具可读性、更容易被理解”，那么怎么才叫 “理解” 了代码呢？难道光是知道了它定义了哪些选项就算了解了一个组件本身么？你是否有接手过他人开发过的一个庞大组件？比如 [你看看这个](https://github.com/vuejs/vue-cli/blob/a09407dd5b9f18ace7501ddb603b95e3
为了避免您之前提到的「避免对任何群体有任何的不敬」，

我将「头大」更改为了「头晕」。

2020-04-25 16:13 UTC, ShenQingchuan commented
There seems to be some tricky skill with Vuepress rendering markdown about the italics style, they can not work without spaces around. 

Sorry for that mistake. 

So I will reedit all  the content before which are similar to the example below soon:

```
- 而组合式 API 让我们可以基于_逻辑关注点_组织代码。
+ 而组合式 API 让我们可以基于 _逻辑关注点_ 组织代码。
```

查看部署效果时发现，Vuepress 在渲染斜体时必须在文字内容前后加上空格才能起效，所以我将会更改我之前因为直接复制您审阅建议中的文字而造成的此疏漏。

抱歉。

2020-04-25 18:07 UTC, Jinjiang reviewed
Reviewed the content before "Verbosity of the Return Statement".
Thanks.

2020-04-25 18:07 UTC, Jinjiang commented on zh/index.md
> +组合式 API 是十分灵活的，因此我们可以在组件间抽象和重用一些逻辑，而不是依赖于一个玄学的 `this` 上下文，一个组合逻辑函数仅仅只依赖于他的参数和一些的 Vue 本身的 API，你可以重用组件内的任何一段逻辑，只要你将它导出成为一个函数即可。你甚至可以通过导出整个 `setup` 函数，做出与 `extends`（继承）等价的效果。
```suggestion
当我们在组件间提取并复用逻辑时，组合式 API 是十分灵活的。一个组合函数仅依赖它的参数和 Vue 全局导出的 API，而不是依赖其黑魔法的 `this` 上下文。你可以将组件内的任何一段逻辑导出为函数以复用它。你甚至可以通过导出整个 `setup` 函数达到和 `extends` 等价的效果。
```

2020-04-25 18:07 UTC, Jinjiang commented on zh/index.md
> +### 逻辑抽象、提取与复用
```suggestion
### 逻辑提取与复用
```

建议将“复用”和“重用”统一，个人倾向于“复用”

2020-04-25 18:07 UTC, Jinjiang commented on zh/index.md
> +👀 让我们来看看这个例子：「**监听鼠标位置**」
```suggestion
让我们看个例子：追踪鼠标的位置。
```

2020-04-25 18:07 UTC, Jinjiang commented on zh/index.md
> +以下是一个组件如何利用该功能的展示:
```suggestion
以下是一个组件如何利用该函数：
```

2020-04-25 18:07 UTC, Jinjiang commented on zh/index.md
> +在组合式 API 版本的文件浏览器组件示例中，我们已经抽象、提取了很多工具代码（例如：`usePathUtils` 和 `useCwdUtils`）到外部文件中，因为我们发现它们也可以被用在其他组件中。
```suggestion
在组合式 API 版本的文件浏览器组件示例中，我们已经提取了很多工具代码 (例如 `usePathUtils` 和 `useCwdUtils`) 到外部文件中，因为我们发现它们也可以被用在其它组件中。
```

2020-04-25 18:07 UTC, Jinjiang commented on zh/index.md
> +同样的逻辑复用，在之前的版本中，我们也有过一些解决方案，比如：`mixins`、高阶组件或是通过 `scoped slots` 实现的低渲染组件。网上已经有很多解释这些实践方式的信息了所以我们不再赘述。这些想法在和组合逻辑函数相比之后，都被发现有明显的缺点。
```suggestion
类似的逻辑复用也可以通过诸如 `mixins`、高阶组件或是 (通过作用域插槽实现的) 无渲染组件的模式达成。网上已经有很多解释这些模式的信息了所以我们不再赘述。更高层面的想法是，相比于组合函数，这些模式都有各自的弊端：
```

2020-04-25 18:07 UTC, Jinjiang commented on zh/index.md
> +- **暴露的数据来源并不清晰。** 在一个模板下运用到的多个 mixins，很难分析得出某个数据是从哪一个 mixins 中得来的
```suggestion
- 渲染上下文中暴露的 property 来源不明。例如在阅读一个运用了多个 mixin 的模板时，很难看出某个 property 是从哪一个 mixin 中注入的。
```

2020-04-25 18:07 UTC, Jinjiang commented on zh/index.md
> +- **命名空间冲突。** 多个 mixins 很可能恰好占用同一个属性名称。
```suggestion
- 命名空间冲突。Mixin 之间的 property 和方法可能有冲突，同时高阶组件也可能和预期的 prop 有命名冲突。
```

中文翻译中保留的英文永远呈现单数状态

2020-04-25 18:07 UTC, Jinjiang commented on zh/index.md
> +- **性能较差。** 在 Vue 中高阶组件可能并不如 React 当中使用的多，原本是为了替代 mixins，但其实这个设计并没有更好，多个 `props` 命名空间依旧会有冲突，`props` 的来源也并不清晰，还额外带来了许多组件级别的、无谓的性能消耗。作用域插槽虽然没有了命名空间冲突、数据来源也清晰了，但是仍然是一个组件级的性能消耗。
```suggestion
- 性能。高阶组件和无渲染组件需要额外的有状态的组件实例，导致性能消耗。
```

2020-04-25 18:07 UTC, Jinjiang commented on zh/index.md
> +在此我们将为您介绍 **Composition API**: 一组低侵入式的、函数式的 API，使得我们能够更灵活地「**组合**」组件的逻辑。
```suggestion
在此我们将为您介绍**组合式 API**：一组低侵入式的、函数式的 API，使得我们能够更灵活地组合组件的逻辑。
```

统一 Composition API 的译法

2020-04-25 18:07 UTC, Jinjiang commented on zh/index.md
> +> `watchEffect` 方法和 2.x 中的 `watch` 选项比较类似，但参数中并不要求将被监听的数据源和副作用回调函数分开。Composition API 同样提供了一个 `watch` 函数，行为与 2.x 选项完全一致。
```suggestion
> `watchEffect` 方法和 2.x 中的 `watch` 选项比较类似，但参数中并不要求将被监听的数据源和副作用回调函数分开。组合式 API 同样提供了一个 `watch` 函数，行为与 2.x 选项完全一致。
```

2020-04-25 18:07 UTC, Jinjiang commented on zh/index.md
> +相比而言，Composition API 具有如下的优势:
```suggestion
相比而言，组合式 API：
```

2020-04-25 18:07 UTC, Jinjiang commented on zh/index.md
> +- 暴露给模板的数据来源十分清晰，因为它们都是被组合逻辑函数返回的值。
```suggestion
- 暴露给模板的 property 来源十分清晰，因为它们都是被组合逻辑函数返回的值。
```

2020-04-25 18:07 UTC, Jinjiang commented on zh/index.md
> +- 不存在命名空间冲突，因为在取值时，可以通过解构的语法进行变量重新命名
```suggestion
- 不存在命名空间冲突，因为组合函数的返回值可以任意命名。
```

2020-04-25 18:07 UTC, Jinjiang commented on zh/index.md
> +- 只是单纯的逻辑复用而没有额外的组件性能消耗
```suggestion
- 不再需要仅为逻辑复用而创建的组件实例。
```

2020-04-25 18:07 UTC, Jinjiang commented on zh/index.md
> +组合式 API 完全可以和现有的 API 配合使用。
```suggestion
组合式 API 完全可以和现有的基于选项的 API 配合使用。
```

2020-04-25 18:07 UTC, Jinjiang commented on zh/index.md
> +- 组合式 API 在 2.x 的选项 (`data`, `computed` 和 `methods`) 之前解析，并且不能提前访问这些选项中定义的属性。
```suggestion
- 组合式 API 会在 2.x 的选项 (`data`、`computed` 和 `methods`) 之前解析，并且不能提前访问这些选项中定义的 property。
```

2020-04-25 18:07 UTC, Jinjiang commented on zh/index.md
> +- `setup()` 函数返回的属性将会被暴露给 `this` 上下文，在 2.x 的选项中也可以访问到。
```suggestion
- `setup()` 函数返回的 property 将会被暴露给 `this`。它们在 2.x 的选项中可以访问到。
```

2020-04-25 18:07 UTC, Jinjiang commented on zh/index.md
> +当下的许多 Vue 插件都将属性注入到了 `this` 上，例如, Vue Router 路由库就注入了 `this.$route` 和 `this.$router`, 而 Vuex 注入了 `this.$store`。这使得类型推断变得棘手，因为每个插件都要求用户为注入的属性和 Vue 本身的类型定义进行关联。
```suggestion
当下许多 Vue 的插件都向 `this` 注入 property。例如 Vue Router 注入 `this.$route` 和 `this.$router`，而 Vuex 注入 `this.$store`。这使得类型推导变得很有技巧性，因为每个插件都要求用户为注入的 property 向 Vue 增加类型定义。
```

建议“type inference”统一译为类型推导，下同

2020-04-25 18:07 UTC, Jinjiang commented on zh/index.md
> +当使用组合式 API 时，我们不再使用 `this`，相应地, 插件将在内部利用[`provide` 和 `inject`](./api.html#依赖注入) 然后暴露一个组合逻辑函数。以下是一个状态管理插件的假设代码:
```suggestion
当使用组合式 API 时，我们不再使用 `this`，取而代之的是，插件将在内部利用 [`provide` 和 `inject`](./api.html#依赖注入) 并暴露一个组合函数。以下是一个插件的假设性代码：
```

2020-04-25 18:07 UTC, Jinjiang commented on zh/index.md
> +生产者部分：
```suggestion
```

这段没有必要特别注明

2020-04-25 18:07 UTC, Jinjiang commented on zh/index.md
> +    // 使用状态仓库 store
```suggestion
    // 使用这个 store
```

2020-04-25 18:07 UTC, Jinjiang commented on zh/index.md
> +注意！这个状态仓库 `store` 只能在 App-层级（即根组件上）提供，`provide` 是[全局 API 更改提案](https://github.com/vuejs/rfcs/blob/master/active-rfcs/0009-global-api-change.md#provide--inject)中提出的 API, 但是消费者组件代码部分中 `useStore` 这类的 AP
```suggestion
注意这个 `store` 也可以通过[全局 API 更改提案](https://github.com/vuejs/rfcs/blob/master/active-rfcs/0009-global-api-change.md#provide--inject)中 App 级别的 `provide` 来提供，但是消费它的组件中的 `useStore` 风格的 API 还是相同的。
```

2020-04-25 18:07 UTC, Jinjiang commented on zh/index.md
> +消费者部分:
```suggestion
消费者的代码：
```

2020-04-25 18:07 UTC, Jinjiang commented on zh/index.md
> +### 引入 Refs 的心智负担
```suggestion
### 引入 Ref 的心智负担
```

2020-04-25 18:07 UTC, Jinjiang commented on zh/index.md
> +Ref「**响应式值引用**」可以说是本提案中唯一的 “新” 概念. 引入它是为了不再依赖 `this` 上下文，而是可以不受太多范围限制地、像一般变量一样获取响应式的值。缺点如下:
```suggestion
Ref 可以说是本提案中唯一的“新”概念。引入它是为了以变量形式传递响应式的值而不再依赖访问 `this`。其弊端如下:
```

2020-04-25 18:07 UTC, Jinjiang commented on zh/index.md
> +## 缺点
```suggestion
## 弊端
```

个人倾向于用“弊端”这个词代替“缺点”，因为这个词感觉上是一个更接近客观描述的中性词。

2020-04-25 18:07 UTC, Jinjiang commented on zh/index.md
> +1. 当使用组合式 API 时, 我们需要一直区别「响应式值引用」与普通的基本类型值与对象，这无疑增加了使用本套 API 的心智负担.
```suggestion
1. 当使用组合式 API 时，我们需要始终区别响应式的值和普通的值与对象，这增加了使用本套 API 的心智负担。
```

2020-04-25 18:07 UTC, Jinjiang commented on zh/index.md
> +   这一层心智负担可以通过名称规范来大大降低（例如：可以把所有的响应式值引用命名为 `xxxRef`），亦或者是使用类型系统。另外，由于代码组织方面的灵活性增加了，组件逻辑会更多地分解成一些短小精悍的函数，它们的上下文都比较简单，也更容易管理这些 refs。
```suggestion
   这一层心智负担可以通过名称规范来大大降低 (例如为所有的 ref 名加类似 `xxxRef` 的后缀)，亦或者是使用类型系统。另外，由于代码组织方面的灵活性增加了，组件逻辑会更多地分解成一些短小精悍的函数，它们的上下文都比较简单，这些 ref 的上限也易于控制。
```

2020-04-25 18:07 UTC, Jinjiang commented on zh/index.md
> +2. 读写 refs 写起来感觉更冗余，因为需要特别访问它的 `.value`。
```suggestion
2. 读写 ref 的操作比普通值的更冗余，因为需要访问 `.value`。
```

2020-04-25 18:07 UTC, Jinjiang commented on zh/index.md
> +   有些建议中提出可以提供编译时的语法糖（类似 Svelte 3）来解决。 虽然它在技术上是可行的，但我们不认为在 Vue 应该默认这么做。(在[与 Svelte 比较](#与-svelte-比较)中有更详细的讨论). 我们保留对其技术上的认可，它可以作为一个 Babel 插件提供给用户。
```suggestion
   有些建议过的编译时语法糖 (类似 Svelte 3) 可以解决这个问题。虽然技术上可行，但我们不认为 Vue 应该默认这么做 (如[与 Svelte 的比较](#与-svelte-的比较)中所讨论的)。或者说，技术上在用户端做一个 Babel 插件是可行的。
```

2020-04-25 18:07 UTC, Jinjiang commented on zh/index.md
> +我们已经讨论过了 “是否可以完全避免引入 Ref 概念，只使用响应性对象”，但是:
```suggestion
我们已经讨论过了是否可以完全避免引入 ref 的概念而只使用响应性对象，但是：
```

2020-04-25 18:07 UTC, Jinjiang commented on zh/index.md
> +- 计算属性时常返回的是基础类型的值, 所以一个 Ref-like 的响应式引用容器是不可避免的。
```suggestion
- 计算属性的 getter 可以返回基础类型值，所以一个类似 ref 的容器是不可避免的。
```

2020-04-25 18:07 UTC, Jinjiang commented on zh/index.md
> +- 一些组合逻辑函数接收的参数或返回的结果为基础类型的值时也需要被包裹成为一个对象，才能够保持其响应性。而如果框架官方不提供一套标准的实现方式，那么最后会有各式各样不同的 API，造成社区生态的分裂。
```suggestion
- 一些组合函数只接收或返回基础类型值，它们也需要被包裹成为一个对象才能够保持其响应性。如果框架不提供标准实现，那么用户最后会发明它们各自的 ref 模式 (从而造成生态的碎片化)。
```

2020-04-25 18:07 UTC, Jinjiang commented on zh/index.md
> +我们预见到, 用户们可能会在何时使用 `ref` 和何时使用 `reactive` 的选择上产生纠结，而首先你要知道的是，**这两者你都必须要了解** 才能够高效地使用组合式 API。专门使用一个将很可能将你的工作无谓地复杂化，或导致没有意义地反复造轮子。
```suggestion
可以理解的是，用户会纠结用 `ref` 还是 `reactive`。而首先你要知道的是，这两者你都必须要了解，才能够高效地使用组合式 API。只用其中一个很可能会使你的工作无谓地复杂化，或反复地造轮子。
```

2020-04-25 18:07 UTC, Jinjiang commented on zh/index.md
> +使用 `ref` 和 `reactive` 的区别，可以通过比较对待一般 JavaScript 逻辑的两种不同方式来体现：
```suggestion
使用 `ref` 和 `reactive` 的区别，可以通过如何撰写标准的 JavaScript 逻辑来比较：
```

2020-04-25 18:07 UTC, Jinjiang commented on zh/index.md
> +// 风格 1: 分开的多个变量
```suggestion
// 风格 1：将变量分离
```

2020-04-25 18:07 UTC, Jinjiang commented on zh/index.md
> +// 风格 2: 一个对象，总领各个属性
```suggestion
// 风格 2：单个对象
```

2020-04-25 18:07 UTC, Jinjiang commented on zh/index.md
> +- 如果使用 `ref`, 我们实际上就是在体现 风格 (1) 中的代码，而使用 refs 只是为了让基础类型的值具有响应性。
```suggestion
- 如果使用 `ref`，我们实际上就是将风格 (1) 转换为使用 ref (为了让基础类型值具有响应性) 的更细致的写法。
```

2020-04-25 18:07 UTC, Jinjiang commented on zh/index.md
> +- 使用 `reactive` 基本与 风格 (2) 是一致的。我们只需要多调用一下 `reactive` 方法就好。
```suggestion
- 使用 `reactive` 和风格 (2) 一致。我们只需要通过 `reactive` 创建这个对象。
```

2020-04-25 18:07 UTC, Jinjiang commented on zh/index.md
> +而只使用 `reactive` 会造成的问题是，组合逻辑函数使用时必须始终保持对其中的属性都进行 “引用化”，以保持响应性，否则解构或扩展两种操作都会丢失响应性:
```suggestion
而只使用 `reactive` 的问题是，使用组合函数时必须始终保持对这个所返回对象的引用以保持响应性。这个对象不能被解构或 spread：
```

2020-04-25 18:07 UTC, Jinjiang commented on zh/index.md
> +// 组合逻辑函数：
```suggestion
// 组合函数
```

2020-04-25 18:07 UTC, Jinjiang commented on zh/index.md
> +// 假设的一个组件
```suggestion
// 消费组件
```

2020-04-25 18:07 UTC, Jinjiang commented on zh/index.md
> +    // 你必须返回 pos 作为返回对象的一个属性，并按 `pos.x` 和 `pos.y` 的方式来来在模板中引用 x 和 y。
```suggestion
    // 你必须返回 `pos` 本身，并按 `pos.x` 和 `pos.y` 的方式在模板中引用 x 和 y。
```

2020-04-25 18:07 UTC, Jinjiang commented on zh/index.md
> +除此之外 [`toRefs`](./api.html#torefs) API 是另一种我们提供出来解决此约束的办法，它将对象的每个属性值都套了一层 `ref`。
```suggestion
[`toRefs`](./api.html#torefs) API 用来提供解决此约束的办法——它将响应式对象的每个 property 都转成了相应的 ref。
```

2020-04-25 18:07 UTC, Jinjiang commented on zh/index.md
> +总结一下，一共有两种办法：
```suggestion
总结一下，一共有两种变量风格：
```

2020-04-25 18:07 UTC, Jinjiang commented on zh/index.md
> +1. 就像你区别声明基础类型变量与对象变量时一样，区别使用 `ref` 和 `reactive`，我们推荐你在此风格下更多地使用 IDE 的语法提示帮助。
```suggestion
1. 就像你在普通 JavaScript 中区别声明基础类型变量与对象变量时一样区别使用 `ref` 和 `reactive`。我们推荐你在此风格下结合 IDE 使用类型系统。
```

2020-04-25 18:07 UTC, Jinjiang commented on zh/index.md
> +2. 所有的地方都用 `reactive`, 然后最后记得在组合逻辑函数返回响应式对象时，使用 `toRefs` 处理一下。这降低了一些关于 refs 的心智负担，但这并不意味着你不需要熟悉这个概念。
```suggestion
2. 所有的地方都用 `reactive`，然后记得在组合函数返回响应式对象时使用 `toRefs`。这降低了一些关于 ref 的心智负担，但并不意味着你不需要熟悉这个概念。
```

2020-04-26 01:53 UTC, aomiba commented
this pr is awesome, I love it
perhaps I can help

is there something way I can commit on this pr instead of create another pr(that's way is not pure)

2020-04-26 01:59 UTC, aomiba commented
> this pr is awesome, I love it
> perhaps I can help
> 
> is there something way I can commit on this pr instead of create another pr(that's way is not pure)

@Jinjiang

2020-04-26 02:00 UTC, ShenQingchuan commented on zh/index.md
> +而只使用 `reactive` 会造成的问题是，组合逻辑函数使用时必须始终保持对其中的属性都进行 “引用化”，以保持响应性，否则解构或扩展两种操作都会丢失响应性:
Spread 参阅 [MDN 文档此处](https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Operators/Spread_syntax)，提供参考翻译词汇：「展开」

2020-04-26 02:07 UTC, ShenQingchuan commented
> this pr is awesome, I love it
perhaps I can help

is there something way I can commit on this pr instead of create another pr(that's way is not pure)

Hi ! I am so glad that you're interested in this PR, and I would like to request you to do some pre-review for the section `API Reference` in order to improve the efficiency of review and proofreading.

你好！很高兴也很荣幸您能参与到中文翻译的 PR 当中来，如果可能的话，您可以帮助 @Jinjiang 提前做一些 `API Reference` 章节的审阅校对工作，提出您的宝贵意见！

2020-04-26 02:12 UTC, ShenQingchuan commented
@aomiba 

Maybe you can provide some format for your suggestions like the example below, just like a code review.

1. First, give an reference of where the target is:
> `-` 就像你区别声明基础类型变量与对象变量时一样，区别使用 `ref` 和 `reactive`，我们推荐你在此风格下更多地使用 IDE 的语法提示帮助。`

2. Provide your suggestion.
> `+` 就像你在普通 JavaScript 中区别声明基础类型变量与对象变量时一样区别使用 `ref` 和 `reactive`。我们推荐你在此风格下结合 IDE 使用类型系统。

This is more effiency for me to modified the content ! Thanks a lot !

2020-04-26 02:15 UTC, ShenQingchuan commented
> > this pr is awesome, I love it
> > perhaps I can help
> > is there something way I can commit on this pr instead of create another pr(that's way is not pure)
> 
> @Jinjiang

BTW, JinJang may not be in the same time zone as ours ...

2020-04-26 02:24 UTC, aomiba commented
> > > this pr is awesome, I love it
> > > perhaps I can help
> > > is there something way I can commit on this pr instead of create another pr(that's way is not pure)
> > 
> > 
> > @Jinjiang
> 
> BTW, JinJang may not be in the same time zone as ours ...

谢谢你的指引， 我先尝试一下

2020-04-26 02:38 UTC, Jinjiang commented
> There seems to be some tricky skills with Vuepress rendering markdown about the italics style, they can not work without spaces around. 
> 
> 
> 
> Sorry for that mistake. 
> 
> 
> 
> So I will reedit all  the content before which are similar to the example below soon:
> 
> 
> 
> ```
> 
> - 而组合式 API 让我们可以基于_逻辑关注点_组织代码。
> 
> + 而组合式 API 让我们可以基于 _逻辑关注点_ 组织代码。
> 
> ```
> 
> 
> 
> 查看部署效果时发现，Vuepress 在渲染斜体时必须在文字内容前后加上空格才能起效，所以我将会更改我之前因为直接复制您审阅建议中的文字而造成的此疏漏。
> 
> 
> 
> 抱歉。

试一下星号

2020-04-26 03:13 UTC, Jinjiang commented
> > > > this pr is awesome, I love it
> > > > perhaps I can help
> > > > is there something way I can commit on this pr instead of create another pr(that's way is not pure)
> > > 
> > > 
> > > @Jinjiang
> > 
> > 
> > BTW, JinJang may not be in the same time zone as ours ...
> 
> 谢谢你的指引， 我先尝试一下

如 @ShenQingchuan 所述，可以帮忙同步看一下 API Reference 的翻译。另外术语和书写格式方面可以参考：https://github.com/vuejs/cn.vuejs.org/wiki

2020-04-26 04:28 UTC, yili-edab requested changes
测试一下 review 功能

2020-04-26 04:28 UTC, aomiba commented on zh/api.md
> +# API Reference
```suggestion
# API 手册
```

2020-04-26 04:58 UTC, yili-edab requested changes
some suggestion

2020-04-26 04:58 UTC, aomiba commented on zh/api.md
> +- **何时调用？**
```suggestion
- **调用时机**
```

2020-04-26 04:58 UTC, aomiba commented on zh/api.md
> +  在组件实例创建时，`setup` 会在初始化 props 后立即调用。从生命周期来看，它会在 `beforeCreate` 前被调用。
```suggestion
创建组件实例，然后初始化 `props` ，紧接着就调用`setup` 函数。从生命周期钩子的视角来看，它会在 `beforeCreate` 钩子之前被调用
```

2020-04-26 04:58 UTC, aomiba commented on zh/api.md
> +- **与模板一起使用时的注意事项**
```suggestion
- **模板中使用**
```

2020-04-26 04:58 UTC, aomiba commented on zh/api.md
> +- **配合 render 函数 / JSX 的用法**
```suggestion
- ** 渲染函数 / JSX 中使用**
```

2020-04-26 04:58 UTC, aomiba commented on zh/api.md
> +- **Usage of `this`**
```suggestion
- **`this`的用法**
```

2020-04-26 04:58 UTC, aomiba commented on zh/api.md
> +## 响应式系统相关 API
```suggestion
## 响应式 API
```

2020-04-26 04:58 UTC, aomiba commented on zh/api.md
> +传入一个对象并返回原始对象的响应代理。等同于 2.x 的 `Vue.observable()`
```suggestion
接收一个普通对象然后返回该普通对象的响应式代理。等同于 2.x 的 `Vue.observable()`
```

2020-04-26 04:58 UTC, aomiba commented on zh/api.md
> +响应式转换是 “深层递归”：它影响所有内部的属性。基于 ES2015 的 Proxy 代理实现，返回的代理对象 **不等于** 原始对象。我们建议 **仅使用代理对象** 而避免依赖原始对象。
```suggestion
响应式转换是 “深层的”：会影响对象内部所有嵌套属性。基于 ES2015 的 Proxy 代理实现，返回的代理对象 **不等于** 原来的普通对象。官方建议 **仅使用代理对象** 而避免使用原来的普通对象。
```

2020-04-26 13:06 UTC, ShenQingchuan commented on zh/api.md
> +## 响应式系统相关 API
这里我建议暂时保留为「 响应式系统 API 」
因为 “响应式 API” 听上去感觉这个 API 具有响应性，但其实它是响应式系统中暴露的 API

2020-04-27 00:59 UTC, aomiba commented on zh/api.md
> +## 响应式系统相关 API
好

2020-04-27 04:57 UTC, yili-edab requested changes
some suggestion before **Reactivity APIs** section of api.md

2020-04-27 04:57 UTC, aomiba commented on zh/api.md
> +        // expose to template
```suggestion
        // 暴露给模板
```

2020-04-27 04:57 UTC, aomiba commented on zh/api.md
> +  注意 `setup` 返回的 ref 在模板中会自动解开，不需要写 `.value`。
```suggestion
  注意 `setup` 返回的 ref 类型的数据在模板中会自动解开，不需要写 `.value`。
```

2020-04-27 04:57 UTC, aomiba commented on zh/api.md
> +  `setup` 也可以返回一个能使用同作用域下 reactive 状态的渲染函数：
```suggestion
  `setup` 可以返回一个函数，函数内部可以直接使用在该作用域中声明的 `reactive`  类型数据：
```

2020-04-27 04:57 UTC, aomiba commented on zh/api.md
> +  然而不要解构 `props` 对象，那样会使其失去响应：
```suggestion
  然而**不要**解构 `props` 对象，那样会使其失去响应式的功能：
```

2020-04-27 04:57 UTC, aomiba commented on zh/api.md
> +  在开发过程中，组件内尝试修改 `props` 时将会报出警告。
```suggestion
  在开发过程中， `props` 对象对用户空间代码时不可变的（用户代码尝试修改 `props` 时会触发警告）
```

2020-04-27 04:57 UTC, aomiba commented on zh/api.md
> +  第二个参数提供了一个包含 2.X APIs `this` 属性的上下文：
```suggestion
  第二个参数提供了一个上下文对象，这个对象暴露了一些可选的 property 列表，和 Vue 2.x APIs 合并在 `this` 上的是一致的：
```

2020-04-27 04:57 UTC, aomiba commented on zh/api.md
> +  `attrs` 和 `slots` 都是组件实例上对应的代理对象，可以确保在更新变化后显示最新值：
```suggestion
  `attrs` 和 `slots` 都是内部组件实例上对应值的代理，可以确保在更新后仍然是最新值。所以我们可以放心的解构他们，并且不用担心后面访问到了以前的值：
```

2020-04-27 04:57 UTC, aomiba commented on zh/api.md
> +  - 将 `props` 独立出来作为第一个参数，是为了让 TypeScript 对 props 有更好对类型推导，不会和上下文中的其他属性相混淆。这也使得与 `setup` 、 `render` 和其他使用了 TSX 的函数式组件的参数签名保持一致。
```suggestion
  - 将 `props` 独立出来作为第一个参数，可以让 TypeScript 对 `props` 单独做类型推导，不会和上下文中的其他属性相混淆。这也使得 `setup` 、 `render` 和其他使用了 TSX 的函数式组件的签名保持一致。
```

2020-04-27 04:57 UTC, aomiba commented on zh/api.md
> +      this // 这里 `this` 不是你想要的意思！
```suggestion
      this // 这里 `this` 和你期望的不一样（你可能希望他是当前组件实例对象吧，但是它**不是**）！
```

2020-04-27 04:57 UTC, aomiba commented on zh/api.md
> +    /*
建议这里关于 `this` 的注释都删掉， 因为 js 的 `this` 不是几句能说清楚的，这里也有歧义

2020-04-27 06:03 UTC, ShenQingchuan commented on zh/api.md
> +  注意 `setup` 返回的 ref 在模板中会自动解开，不需要写 `.value`。
根据之前 JinJang 审阅的建议，对于 Composition API 中引入的 ref 概念，我们倾向于不翻译，保留 ref ，而无需重复说其是 `ref 类型的数据`。

感谢您的建议。

2020-04-27 06:14 UTC, ShenQingchuan commented on zh/api.md
> +  第二个参数提供了一个包含 2.X APIs `this` 属性的上下文：
> 第二个参数提供了一个上下文对象，这个对象暴露了一些可选的 property 列表，和 Vue 2.x APIs 合并在 `this` 上的是一致的：

这样翻译我个人认为是有误的，可能导致读者理解歧义。
因为经过查阅 [`@vue/composition-api` 中的源代码](https://github.com/vuejs/composition-api/blob/master/src/component/component.ts#L43)，`setup(props, ctx)` 中的 ctx 类型定义为：

```ts
export interface SetupContext {
  readonly attrs: Record<string, string>;
  readonly slots: { [key: string]: (...args: any[]) => VNode[] };
  readonly parent: ComponentInstance | null;
  readonly root: ComponentInstance;
  readonly listeners: { [key: string]: Function };

  emit(event: string, ...args: any[]): void;
}
```

故而不应该翻译为 `与 2.x this 上是一致的`

我提供的参考翻译修改：
「 第二个参数提供了一个上下文对象，从原来 2.x 中 `this` 选择性地暴露了一些 property。 」

2020-04-27 06:18 UTC, ShenQingchuan commented on zh/api.md
> +  `attrs` 和 `slots` 都是组件实例上对应的代理对象，可以确保在更新变化后显示最新值：
根据 JinJang 对 RFC 内容部分的审阅，我感到：
- 尽量避免出现 `我们` 和 `他们` 等口语化词汇
- 尽量使用更书面化的语言

我提供的修改参考：
「 `attrs` 和 `slots` 都是内部组件实例上对应值的代理，可以确保在更新后仍然是最新值。所以可以解构，无需担心后面访问到过期的值 」

2020-04-27 06:25 UTC, aomiba commented on zh/api.md
> +  第二个参数提供了一个包含 2.X APIs `this` 属性的上下文：
你这样是对的

2020-04-27 11:28 UTC, loveyunk commented on zh/index.md
> +想想看我们该如何跟别的开发者同步理解上面链接里那样的一个大型组件。你大概会从“这个组件在处理 X、Y 与 Z”开始，而是“这个组件有这些数据 property、这些计算属性和这些方法”。
想想看我们该如何跟别的开发者同步理解上面链接里那样的一个大型组件。你大概会从“这个组件在处理 X、Y 与 Z”开始，而不是“这个组件有这些数据 property、这些计算属性和这些方法”。

2020-04-27 14:25 UTC, loveyunk requested changes

2020-04-27 14:25 UTC, loveyunk commented on zh/index.md
> +想想看我们该如何跟别的开发者同步理解上面链接里那样的一个大型组件。你大概会从“这个组件在处理 X、Y 与 Z”开始，而是“这个组件有这些数据 property、这些计算属性和这些方法”。
```suggestion
想想看我们该如何跟别的开发者同步理解上面链接里那样的一个大型组件。你大概会从“这个组件在处理 X、Y 与 Z”开始，而不是“这个组件有这些数据 property、这些计算属性和这些方法”。
```

2020-04-27 21:21 UTC, Jinjiang reviewed
Reviewed the content before "Appendix"

2020-04-27 21:21 UTC, Jinjiang commented on zh/index.md
> +一些用户提出 `setup()` 函数的返回语句十分重复、冗余，很多是重复劳动。
```suggestion
一些用户会顾虑 `setup()` 的返回语句变得冗长，像是重复劳动。
```

2020-04-27 21:21 UTC, Jinjiang commented on zh/index.md
> +我们相信明确的返回语句对可维护性是有益的。它使我们能够显式地控制暴露给模板的内容，并在跟踪组件中定义模板属性的位置时充当起点。
```suggestion
我们相信明确的返回语句对可维护性是有益的。它使我们能够显式地控制暴露给模板的内容，并作为追踪组件中被定义的模板 property 的起点。
```

2020-04-27 21:21 UTC, Jinjiang commented on zh/index.md
> +建议自动公开在 `setup()` 中声明的变量，使 `return` 语句变为可选的。同样我们不认为这应该是框架官方默认的行为，因为它违背了标准 JavaScript 的直觉。然而，有以下一些可能的方法可以让它在用户中变得不那么繁琐:
```suggestion
有些建议希望自动暴露 `setup()` 中声明的变量，使 `return` 语句变为可选的。再次重申，我们不认为这应该是默认的行为，因为它违背了标准 JavaScript 的直觉。不过还是有一些方法可以让用户侧的工作变少：
```

2020-04-27 21:21 UTC, Jinjiang commented on zh/index.md
> +### 更多的灵活性同样需要更多规范
```suggestion
### 更多的灵活性来自更多的自我克制
```

对 Discipline 的另一种意译，可讨论

2020-04-27 21:21 UTC, Jinjiang commented on zh/index.md
> +许多用户指出，虽然组合式 API 在代码组织方面提供了更多的灵活性，但它也需要开发人员遵守更多的规范来 “正确完成”。有些人担心 API 会让没有经验的人编写出复杂的代码。换句话说，虽然组合式 API 提高了代码质量的上限，但它也降低了下限。
```suggestion
许多用户指出，虽然组合式 API 在代码组织方面提供了更多的灵活性，但它也需要开发人员更多地自我克制来 “正确地完成它”。也有些人担心 API 会让没有经验的人编写出面条代码。换句话说，虽然组合式 API 提高了代码质量的上限，但它也降低了下限。
```

2020-04-27 21:21 UTC, Jinjiang commented on zh/index.md
> +我们在一定程度上同意这一点。但是，我们认为:
```suggestion
我们在一定程度上同意这一点。但是，我们认为：
```

2020-04-27 21:21 UTC, Jinjiang commented on zh/index.md
> +1. 上界的收益远远大于下界的损失。
```suggestion
1. 提升上界的收益远远大于降低下界的损失。
```

2020-04-27 21:21 UTC, Jinjiang commented on zh/index.md
> +一些用户用 Angular 1 的控制器作为例子，来说明这种设计是如何可能导致糟糕代码的。组合式 API 和 Angular 1 控制器之间最大的不同是它不依赖于一个共享的范围上下文。这使得将逻辑划分为单独的函数变得非常容易，这正是 JavaScript 代码组织的核心机制。
```suggestion
一些用户用 Angular 1 的控制器作为例子，来说明这种设计是如何导致糟糕代码的。组合式 API 和 Angular 1 控制器之间最大的不同是它不依赖于一个共享的作用域上下文。这使得将逻辑划分为单独的函数变得非常容易，这正是 JavaScript 代码组织的核心机制。
```

2020-04-27 21:21 UTC, Jinjiang commented on zh/index.md
> +任何 JavaScript 程序都是从一个输入文件开始的(可以将它看作是程序的 `setup()`)。我们根据逻辑关系将程序分解成函数和模块来组织它。**组合式 API 使我们能够对 Vue 组件代码做同样的事情。** 换句话说，编写组织良好的 JavaScript 代码的技能直接转化为编写组织良好的 Vue 代码的技能。
```suggestion
任何 JavaScript 程序都是从一个入口文件开始的 (将它想象为程序的 `setup()`)。我们根据逻辑关注点将程序分解成函数和模块来组织它。**组合式 API 使我们能够对 Vue 组件代码做同样的事情。**换句话说，编写有组织的 JavaScript 代码的技能直接转化为了编写有组织的 Vue 代码的技能。
```

2020-04-27 21:21 UTC, Jinjiang commented on zh/index.md
> +## 升级策略与建议
```suggestion
## 接纳策略
```

个人觉得这里并不需要潜在的“升级”的心智

2020-04-27 21:21 UTC, Jinjiang commented on zh/index.md
> +组合式 API 完全是可选的、可被添加到现有项目中的，也不会对现有的 2.x API 们造成任何影响. 它已经被提供为了一个 2.x 插件，详见[`@vue/composition` 这个库](https://github.com/vuejs/composition-api/). 这个库的基本宗旨是提供一个机会让大家体验新的 API 并收集用户反馈。当前的实现已经与本提案内的内容保持一致, 但是
```suggestion
组合式 API 完全是可被添加的，且不会影响/废弃任何现有的 2.x API。通过 [`@vue/composition` 这个库](https://github.com/vuejs/composition-api/)，它已经以插件的形式在 2.x 中生效了。这个库的基本宗旨是提供一个机会让大家体验新的 API 并收集反馈。当前的实现已经与本提案内的内容保持同步，但是由于插件的技术限制可能会包含一些微观的不一致。随着提案的更新，它也可能会做一些不兼容的变更，所以我们不建议这个阶段在生产环境中使用它。
```

2020-04-27 21:21 UTC, Jinjiang commented on zh/index.md
> +我们会将这一套 API 内建在 Vue 3.0 中，它将与 2.x 的选项式 API 同时存在，两者皆可用。
```suggestion
我们会将这一套 API 内建在 Vue 3.0 中，它将与现有的 2.x 选项同时可用。
```

2020-04-27 21:21 UTC, Jinjiang commented on zh/index.md
> +对于想要在应用程序中仅使用组合式 API 的用户，我们可能会提供一个编译时标记来删除那些仅适用于 2.x 的代码来减小整个库的大小，但这应当是完全可选的。
```suggestion
对于想要在应用程序中仅使用组合式 API 的用户，我们可能会提供一个编译时标记来删除那些仅用于 2.x 选项的代码来减小整个库的大小，这是完全可选的。
```

2020-04-27 21:21 UTC, Jinjiang commented on zh/index.md
> +这个 API 将被定位为一个额外的高级特性，因为它旨在解决的问题主要出现在大型应用程序中。我们不打算彻底修改文档来使用它作为默认建议。相反，它将在文档中有自己的专用部分。
```suggestion
这个 API 将被定位为高级特性，因为它旨在解决的问题主要出现在大型应用程序中。我们不打算彻底修改文档来把它用作默认方案。相反，它将在文档中有自己的专用部分。
```

2020-04-27 22:33 UTC, Jinjiang reviewed
Reviewed all content in `zh/index.md`.

2020-04-27 22:33 UTC, Jinjiang commented on zh/index.md
> +### Class-API 的类型问题
```suggestion
### Class API 的类型问题
```

2020-04-27 22:33 UTC, Jinjiang commented on zh/index.md
> +引入 Class-API 的主要目的是提供一个具有更好的 TypeScript 类型推导，但是，Vue 组件需要将多个源声明的属性合并到一个上下文中，这事实上给基于类的 API 带来了很大挑战。
```suggestion
引入 Class API 的主要目的是提供另一种 API 以更好地支持 TypeScript 类型推导。但是，Vue 组件需要将声明自多个来源的 property 合并到一个 `this` 上下文中，这给基于 Class 的 API 带来了一些挑战。
```

2020-04-27 22:33 UTC, Jinjiang commented on zh/index.md
> +
这里少了一行：

```
One example is the typing of props. In order to merge props onto this, we have to either use a generic argument to the component class, or use a decorator.
```

建议的翻译：

```
Prop 的类型是其中一个例子。为了把 prop 合并到 `this` 中，我们不得不为组件的 Class 使用一个泛型参数，或使用一个 decorator。
```

2020-04-27 22:33 UTC, Jinjiang commented on zh/index.md
> +由于传递给泛型参数的接口（这里的 `Props`）是仅仅是类型标注而已，所以用户仍然需要为 `this` 上的 `props` 代理行为提供一个运行时的 `props` 声明，这种二次声明是多余且笨拙的。
```suggestion
由于传递给泛型参数的 interface 仅仅是类型标注，所以用户仍然需要在 `this` 上为 prop 的代理行为提供其运行时声明。这种二次声明是多余且笨拙的。
```

2020-04-27 22:33 UTC, Jinjiang commented on zh/index.md
> +我们考虑了使用 `@prop` 这样的装饰器来作为替代方案：
```suggestion
我们考虑过用 decorator 作为替代方案：
```

2020-04-27 22:33 UTC, Jinjiang commented on zh/index.md
> +但由于这是依赖「装饰器」这样一个仍然处于 stage-2 的提案，所以在未来这有非常大的不确定性，特别是现在 TypeScript 的实现方案已经完全不是与 TC39 提案相同步的。除此之外，另外没有什么太好的办法能够将定义在 `this.$props` 上的属性类型暴露出来，
```suggestion
使用 decorator 导致它依赖一个带有很大不确定性的 stage-2 提案，特别是现在 TypeScript 的实现方案已经完全不是与 TC39 提案相同步的。除此之外没有什么太好的办法能够将定义在 `this.$props` 上的 prop 类型声明暴露出来，
```

取消这里的折行

2020-04-27 22:33 UTC, Jinjiang commented on zh/index.md
> +这使得难以支持 TSX。另外用户们可能还会为某些使用装饰器设置的 prop 设置默认值，但这其实并不可用。
```suggestion
从而破坏 TSX 支持。另外用户也会假设他们可以通过 `@prop message: string = 'foo'` 为某些 prop 声明默认值，但技术上这其实并不可用。
```

2020-04-27 22:33 UTC, Jinjiang commented on zh/index.md
> +所以说，目前还没有很好的办法利用上下文的类型标注来推导方法及其参数的类型，这意味着传递给类 `render` 函数的参数不能利用类的其他属性来做类型推导。
```suggestion
加之目前还没有很好的办法利用上下文的类型标注来推导 class 方法的参数——这意味着传递给一个 class 的 `render` 函数不能基于 class 的其它 property 来推导参数类型。
```

2020-04-27 22:33 UTC, Jinjiang commented on zh/index.md
> +- 一般来说，更符合习惯的 JavaScript 代码的直觉
```suggestion
- 一般来说更符合惯用的 JavaScript 代码的直觉；
```

2020-04-27 22:33 UTC, Jinjiang commented on zh/index.md
> +- 对调用顺序并没有那么严格，因而可以因境况而更好地调整
```suggestion
- 不需要顾虑调用顺序，也可以用在条件语句中；
```

2020-04-27 22:33 UTC, Jinjiang commented on zh/index.md
> +- 不会每次重新渲染都执行，因而可以大大降低垃圾回收的压力
```suggestion
- 不会在每次渲染时重复执行，以降低垃圾回收的压力；
```

2020-04-27 22:33 UTC, Jinjiang commented on zh/index.md
> +- 不存在内联回调函数导致子组件永远更新的问题
```suggestion
- 不存在内联处理函数导致子组件永远更新的问题，也不需要 `useCallback`；
```

2020-04-27 22:33 UTC, Jinjiang commented on zh/index.md
> +- 如果用户的依赖传递出现失误，“useEffect” 和 “useMemo” 可能会捕获过时的变量。Vue 的自动依赖跟踪确保观察者和计算值总是准确无误
```suggestion
- 不存在忘记记录依赖的问题，也不需要“useEffect”和“useMemo”并传入依赖数组以捕获过时的变量。Vue 的自动依赖跟踪可以确保侦听器和计算值总是准确无误。
```

2020-04-27 22:33 UTC, Jinjiang commented on zh/index.md
> +#### 计算属性 与 Ref
```suggestion
#### 计算状态 与 Ref
```

2020-04-27 22:33 UTC, Jinjiang commented on zh/index.md
> +有时候，我们会需要一个依赖于其他状态的状态，在 Vue 中这是通过*计算属性*来处理的。我们可以使用 `computed` API 直接创建一个计算属性：
```suggestion
有时候，我们会需要一个依赖于其他状态的状态，在 Vue 中这是通过*计算属性*来处理的。我们可以使用 `computed` API 直接创建一个计算值：
```

2020-04-27 22:33 UTC, Jinjiang commented on zh/index.md
> +现在我们可以通过引用来传递计算属性值，也不需要担心其响应式特性会丢失了。当然代价就是：为了获取最新的值，我们每次都需要写 `.value`。
```suggestion
现在我们可以通过引用来传递计算值，也不需要担心其响应式特性会丢失了。当然代价就是：为了获取最新的值，我们每次都需要写 `.value`。
```

2020-04-27 22:33 UTC, Jinjiang commented on zh/index.md
> +除了计算属性的 ref，我们还可以使用 `ref` API 直接创建一个可变更的普通的 ref：
```suggestion
除了计算值的 ref，我们还可以使用 `ref` API 直接创建一个可变更的普通的 ref：
```

2020-04-27 22:33 UTC, Jinjiang commented on zh/index.md
> +到此我们已经覆盖了组件的纯状态层面：响应式状态、计算属性和用户输入时的状态变更。但是一个组件可能还会产生其它副作用——例如在控制台打印信息、发送 AJAX 请求或在全局 `window` 对象上设置事件监听器。这些副作用大多会发生在如下时间节点上：
```suggestion
到此我们已经覆盖了组件的纯状态层面：响应式状态、计算状态和用户输入时的状态变更。但是一个组件可能还会产生其它副作用——例如在控制台打印信息、发送 AJAX 请求或在全局 `window` 对象上设置事件监听器。这些副作用大多会发生在如下时间节点上：
```

2020-04-27 22:33 UTC, Jinjiang commented on zh/index.md
> +- 计算属性的 getter 可以返回基础类型值，所以一个类似 ref 的容器是不可避免的。
```suggestion
- 计算值的 getter 可以返回基础类型值，所以一个类似 ref 的容器是不可避免的。
```

2020-04-27 22:33 UTC, Jinjiang commented on zh/index.md
> +我们敬佩 React Hooks 的创造性，它也是本提案的主要灵感来源，然而上面提到的一些其设计中的问题与缺陷，我们在 Vue 的响应式模型中恰好顺带地给解决了。
```suggestion
我们感谢 React Hooks 的创造性，它也是本提案的主要灵感来源，然而上面提到的一些问题存在与其设计之中，且我们发现 Vue 的响应式模型恰好为解决这些问题提供了一种思路。
```

2020-04-27 22:33 UTC, Jinjiang commented on zh/index.md
> +### 与 svelte 比较
```suggestion
### 与 Svelte 比较
```

2020-04-27 22:33 UTC, Jinjiang commented on zh/index.md
> +Svelte 的代码看起来更简洁，因为它在编译时期做了以下工作:
```suggestion
Svelte 的代码看起来更简洁，因为它在编译时做了以下工作：
```

2020-04-27 22:33 UTC, Jinjiang commented on zh/index.md
> +- 隐式地将整个 `script` 块（ `import` 语句除外）包装到每个组件实例调用的函数中（并不是只执行一次）
```suggestion
- 隐式地将整个 `<script>` 块 (import 语句除外) 包装到一个函数中，该函数会被每个组件实例调用 (而不是只执行一次)
```

2020-04-27 22:33 UTC, Jinjiang commented on zh/index.md
> +- 隐式在变量更改时注入了响应性
```suggestion
- 隐式地为变量的变更注册响应性
```

2020-04-27 22:33 UTC, Jinjiang commented on zh/index.md
> +- 隐式地向呈现上下文公开所有范围内的变量
```suggestion
- 隐式地向渲染上下文暴露所有作用域内的变量
```

2020-04-27 22:33 UTC, Jinjiang commented on zh/index.md
> +- 将 `$` 语句编译为重新执行的代码
```suggestion
- 将 `$` 语句编译为重复执行的代码
```

2020-04-27 22:33 UTC, Jinjiang commented on zh/index.md
> +从技术上讲，我们在 Vue 中也可以通过可能的 Babel 插件做到这些，但我们不想这样做的原因是：**想要与标准 JavaScript 保持一致**。
```suggestion
从技术上讲，我们在 Vue 中也可以 (通过用户侧的 Babel 插件是可以做到的) 做到。我们没有这样做的主要原因是**与标准 JavaScript 保持一致**。
```

去掉这里的折行

2020-04-27 22:33 UTC, Jinjiang commented on zh/index.md
> +如果您从 Vue 单文件组件的 `script` 块中提取代码，我们希望它与标准的 ES 模块完全相同。另一方面，Svelte 的 `script` 块中的代码在技术上已经不再是标准的 JavaScript 了，这种基于编译器的方法存在很多问题:
```suggestion
如果要在 Vue 文件中提取 `<script>` 块的代码，我们希望它与标准的 ES 模块完全相同。Svelte 中 `<script>` 块的代码在技术上已经不再是标准的 JavaScript 了。我们觉得这种基于编译器的方法存在一些问题：
```

2020-04-27 22:33 UTC, Jinjiang commented on zh/index.md
> +1. 在有或没有编译时，其代码的工作方式是不同。作为一个渐进的框架，许多 Vue 用户可能 希望/需要/必须 在没有任何构建配置的情况下使用，因此编译后的版本不能是默认的。另一方面，Svelte 将自己定位为一种编译器，只能搭配构建步骤一起使用。这也都是两个框架都在有意识地根据自己的目标进行权衡的结果。
```suggestion
1. 在有或没有编译时，代码工作的方式不同。作为一个渐进的框架，许多 Vue 用户可能希望/需要/不得不在没有构建环节的情况下使用，因此编译的版本不会作为默认方案。另一方面，Svelte 将自己定位为一种编译器且_只_用于构建环节。这是两个框架都在做的有意识的权衡。
```

2020-04-27 22:33 UTC, Jinjiang commented on zh/index.md
> +2. 代码在组件内部和外部的工作方式不同。当试图从一个 Svelte 的组件中提取逻辑并将其放入标准的 JavaScript 文件时，我们将失去那看上去神奇、简洁的语法糖，而不得不退回到 [一个更冗长的底层 API](https://svelte.dev/docs#svelte_store)。
```suggestion
2. 代码在组件内部和外部的工作方式不同。当试图从一个 Svelte 的组件中提取逻辑并将其放入标准的 JavaScript 文件时，我们将失去那些神奇简洁的语法糖，而不得不退回到[更冗长的底层 API](https://svelte.dev/docs#svelte_store)。
```

2020-04-27 22:33 UTC, Jinjiang commented on zh/index.md
> +3. Svelte 的响应性编译只适用于顶层变量，它不涉及函数中声明的变量, 所以我们 [无法将响应应式状态封装在组件内声明的函数中](https://svelte.dev/repl/4b000d682c0548e79697ddffaeb757a3?version=3.6.2)。这给自带函数的代码组织带来了无可避免的约束，正如我们在这个提案中所演示的，这对于保持大型组件的可维护性非常重要。
```suggestion
3. Svelte 的响应性编译只适用于顶层变量——它不触及函数内声明的变量，所以我们[无法将响应式状态封装在一个函数中并声明在一个组件内](https://svelte.dev/repl/4b000d682c0548e79697ddffaeb757a3?version=3.6.2)。这在通过函数来组织代码时带来了不小的约束，正如我们在这个提案中所演示的，这对于保持大型组件的可维护性非常重要。
```

2020-04-27 22:33 UTC, Jinjiang commented on zh/index.md
> +4. [非标准语义使得它与 TypeScript 相集成十分困难](https://github.com/sveltejs/svelte/issues/1639).
```suggestion
4. [非标准语义使其与 TypeScript 的集成存在困难](https://github.com/sveltejs/svelte/issues/1639)。
```

2020-04-27 22:33 UTC, Jinjiang commented on zh/index.md
> +这并不是说 Svelte 3 的方案是一个很坏的设计，事实上，它是一个非常创新的想法，我们非常尊重 Rich 的工作。但是基于 Vue 的设计限制和最终目标上的不同，我们必须做出不同的权衡。
```suggestion
这并不是说 Svelte 3 不好——事实上，它是一个非常创新的想法，并且我们高度尊重 Rich 的工作。但是基于 Vue 在设计上的克制及其目标，我们不得不做出不同的权衡。
```

2020-04-27 22:38 UTC, Jinjiang commented
至此 `zh/index.md` 的部分已经进行了一次完整的 review，我可能倾向于把 `zh/api.md` 的部分留给 @aomiba 来 review。考虑到我个人精力的问题，我觉得经过两人以上同时看过的翻译某种角度是值得信赖的。所以在我和 @aomiba 分别确认两份文档的翻译不存在异议的情况下，我会 approve 这个 PR。

`zh/api.md` 的部分我在 approve/merge 之后仍会抽时间做二次 review。

@yyx990803 WDYT?

2020-04-28 01:43 UTC, ShenQingchuan commented on zh/index.md
> +### 更多的灵活性同样需要更多规范
我想提议为：「自我约束」
以表达遵照特性规范来合理合规的使用 API

2020-04-28 01:47 UTC, ShenQingchuan commented on zh/index.md
> +### 更多的灵活性同样需要更多规范
呃... 但似乎，约束与灵活本身又有些对冲反义...
但这里应该想表达的就是这种 避免走极端的 意思。

我最终还是采用您的提议「自我克制」

2020-04-28 01:52 UTC, ShenQingchuan commented on zh/index.md
> +组合式 API 完全是可选的、可被添加到现有项目中的，也不会对现有的 2.x API 们造成任何影响. 它已经被提供为了一个 2.x 插件，详见[`@vue/composition` 这个库](https://github.com/vuejs/composition-api/). 这个库的基本宗旨是提供一个机会让大家体验新的 API 并收集用户反馈。当前的实现已经与本提案内的内容保持一致, 但是
这段翻译非常棒！

2020-04-28 04:04 UTC, yili-edab reviewed
some suggestion before `watch`
仅供参考

另： 你把 `watchEffect(callabck)` 里面的 callback 翻译成了句柄函数，刚开始看的时候容易让我想到 window句柄，多看一点也能接受。

2020-04-28 04:04 UTC, yangli-edabear commented on zh/api.md
> +  **`this` 在 `setup()` 中不可用。** 由于 `setup()` 在解析 2.x 选项前被调用，`setup()` 中的 `this` 将与 2.x 选项中的 `this` 完全不同。同时在 `setup()` 和 2.x 选项中使用 `this` 时将造成混乱。在 `setup()` 中避免这种情况的另一个原因是：这对于初学者来说可能并没有完全弄清楚 `this` 当时所
```suggestion
  **`this` 在 `setup()` 中不可用。** 由于 `setup()` 在解析 2.x 选项前被调用， `setup()` 中的 `this` （如果让其可用）与 2.x 其他选项中的 `this` 完全不同。同时在 `setup()` 和 2.x 其他选项中使用 `this` 会造成混乱。避免在 `setup()` 中使用 `this` 另一个原因是：这对于初学者来说，混淆这两种情况的 `this` 是非常常见的错误：
```

2020-04-28 04:04 UTC, yangli-edabear commented on zh/api.md
> +接收一个普通对象然后返回该普通对象的响应式代理。等同于 2.x 的 `Vue.observable()`
great, 我非常同意把这里 `original` 翻译为普通对象，而不是原始对象

2020-04-28 04:04 UTC, yangli-edabear commented on zh/api.md
> +- **在模板中访问**
```suggestion
- **模板中访问**
```

2020-04-28 04:04 UTC, yangli-edabear commented on zh/api.md
> +  当 ref 作为渲染上下文返回（`setup()` 返回的对象）并在模板中使用时，它会自动解套，无需在模板内额外书写 `.value`：
```suggestion
  当 ref 作为渲染上下文的属性被返回（`setup()` 返回的对象）并在模板中使用时，它会自动解开，无需在模板内额外书写 `.value`：
```

2020-04-28 04:04 UTC, yangli-edabear commented on zh/api.md
> +  当 ref 作为 reactive 对象的属性被访问或修改时，也将自动解套 value 值，其行为类似普通属性：
```suggestion
  当 ref 作为 reactive 对象的属性被访问或变更时，也将自动解开 value 值，让其表现得与普通属性类似：
```

2020-04-28 04:04 UTC, yangli-edabear commented on zh/api.md
> +  注意当嵌套在响应式 `Object` 中时，ref 才会解套。从 `Array` 或诸如 `Map` 等原生集合类中访问 ref 时，不会自动解套：
```suggestion
  注意只有当 ref 是`响应式对象` 的嵌套属性时，才会自动解开。从 `Array` 或 `Map` 等原生集合类中访问 ref 时，不会自动解开：
```

2020-04-28 04:04 UTC, yangli-edabear commented on zh/api.md
> +传入一个句柄函数，并返回一个默认不可手动修改的 ref 对象。
```suggestion
传入一个 getter 函数，并返回一个默认不可手动修改的 ref 对象。
```

2020-04-28 04:04 UTC, yangli-edabear commented on zh/api.md
> +或者使用 `get` 和 `set` 函数创建一个可手动修改的计算属性。
```suggestion
或者传入一个对象，该对象拥有 `get` 和 `set` 函数，创建一个可手动修改的计算属性。
```

2020-04-28 04:04 UTC, yangli-edabear commented on zh/api.md
> +传入一个对象（响应式或普通皆可）或 响应式值引用 ref 并返回一个 **只读** 的代理到原始对象。对于一个只读的代理对象，访问任何内部更深层的属性也都是只读的。
```suggestion
传入一个对象（响应式或普通）或  ref ，返回这些值的 **只读** 代理。只读代理的特性是"深层的"，访问任何内部嵌套的属性也都是只读的。
```

2020-04-28 04:04 UTC, yangli-edabear commented on zh/api.md
> +监听响应依赖开始之后，其句柄函数立即调用，并在其依赖改变时触发响应。
句柄函数，在这里什么意思？

2020-04-28 04:04 UTC, yangli-edabear commented on zh/api.md
> +监听响应依赖开始之后，其句柄函数立即调用，并在其依赖改变时触发响应。
```suggestion
立即执行这个函数并且响应式跟踪依赖，并在其依赖改变时再次执行这个函数。
```

2020-04-28 04:04 UTC, yangli-edabear commented on zh/api.md
> +#### 手动停止监听
根据 [wki](https://github.com/vuejs/cn.vuejs.org/wiki)
list  监听
observe/watch  侦听

2020-04-28 04:04 UTC, yangli-edabear commented on zh/api.md
> +#### 手动停止监听
```suggestion
#### 停止侦听
```

2020-04-28 04:04 UTC, yangli-edabear commented on zh/api.md
> +#### 清除被动响应
这里不好翻译，提供两个参考
1. 失效副作用
2. 清理副作用

2020-04-28 04:04 UTC, yangli-edabear commented on zh/api.md
> +- 监听回调即将重新调用时
```suggestion
- 侦听回调被重新调用
```

2020-04-28 04:04 UTC, yangli-edabear commented on zh/api.md
> +- 停止监听时 (如果在 `setup()` 或 生命周期钩子函数中使用了 `watchEffect`, 则在卸载组件时)
```suggestion
- 侦听器被停止 (在 `setup()` 或 生命周期钩子函数中使用了 `watchEffect`, 则在卸载组件时)
```

2020-04-28 04:04 UTC, yangli-edabear commented on zh/api.md
> +#### 响应句柄刷新时间
```suggestion
#### 响应句柄刷新时机
```

2020-04-28 04:04 UTC, yangli-edabear commented on zh/api.md
> +#### 监听器调试
```suggestion
#### 侦听器调试
```

2020-04-28 04:04 UTC, yangli-edabear commented on zh/api.md
> +`onTrack` 和 `onTrigger` 选项可用于调试一个监听的行为。
```suggestion
`onTrack` 和 `onTrigger` 选项可用于调试一个侦听器的行为。
```

2020-04-28 04:04 UTC, aomiba commented on zh/api.md
> +- 当监听回调因依赖项变化被触发时，将调用 `onTrigger`
```suggestion
- 依赖项变更导致监听器被触发时，将调用 `onTrigger`
```

2020-04-28 04:11 UTC, ShenQingchuan commented on zh/api.md
> +  **`this` 在 `setup()` 中不可用。** 由于 `setup()` 在解析 2.x 选项前被调用，`setup()` 中的 `this` 将与 2.x 选项中的 `this` 完全不同。同时在 `setup()` 和 2.x 选项中使用 `this` 时将造成混乱。在 `setup()` 中避免这种情况的另一个原因是：这对于初学者来说可能并没有完全弄清楚 `this` 当时所
我个人倾向于直接说出：`setup` 的 `this` 和 2.x 的微妙 `this` 完全不同
以避免 `（如果让其可用）`给读者带来的思维混乱。

Thanks.

2020-04-28 04:12 UTC, ShenQingchuan commented on zh/api.md
> +  当 ref 作为渲染上下文返回（`setup()` 返回的对象）并在模板中使用时，它会自动解套，无需在模板内额外书写 `.value`：
已经更新为：
「 `当 ref 作为渲染上下文的属性返回（即在`setup()` 返回的对象中）并在模板中使用时，它会自动解套，无需在模板内额外书写 `.value`：` 」

2020-04-28 04:16 UTC, ShenQingchuan commented on zh/api.md
> +  当 ref 作为 reactive 对象的属性被访问或修改时，也将自动解套 value 值，其行为类似普通属性：
源引 Vue.js 官方中文文档的翻译建议：
属性一词在英语中可以对应 `attribute` 和 `property`。

我个人接受并十分赞同这种，A 语言中 一词 对应 B 语言中 两词 的「保留翻译」方式。
因为这应当是语言系统对某概念表达习惯的不同。

所以我们对 属性一词 应保持谨慎，不过在此处，其实翻译为 “属性” 当然也未尝不可。

2020-04-28 04:19 UTC, ShenQingchuan commented on zh/api.md
> +  注意当嵌套在响应式 `Object` 中时，ref 才会解套。从 `Array` 或诸如 `Map` 等原生集合类中访问 ref 时，不会自动解套：
@aomiba 对于概念当中：

`reactive` 和 `ref` 这样和 API 强关联对应对概念，我想是否可以保留，不翻译，以方便读者读到这里对时候能够更快地反应过来。

我此处已经改为：

> 注意当嵌套在 reactive `Object` 中时，ref 才会解套。从 `Array` 或者 `Map` 等原生集合类中访问 ref 时，不会自动解套：

Just suggestion, thanks.

2020-04-28 04:22 UTC, ShenQingchuan commented
> 刚开始看的时候容易让我想到 window句柄，多看一点也能接受。

其实句柄这个词，我一开始在使用时也有犹豫，我本来是想用这个词来强对应 `handler`，然而现在经过 JinJang 前期对 `index.md` 的审阅，我发现其实直接把 `watchEffect(callback)` 当中的这个 callback 就翻译为 **副作用函数** 可能更好。

因为这个函数本身的逻辑就是一次响应所带来的副作用，对此我也想参考您的意见。

感谢。

2020-04-28 04:23 UTC, ShenQingchuan commented on zh/api.md
> +#### 手动停止监听
@aomiba 监听 -> 侦听的 更改已经根据 wiki 完成，感谢您。

2020-04-28 04:25 UTC, ShenQingchuan commented on zh/api.md
> +监听响应依赖开始之后，其句柄函数立即调用，并在其依赖改变时触发响应。
我把您当中说的 `这个` 改为了 `传入的一个`，以避免读者读到这里的困惑。

2020-04-28 04:28 UTC, ShenQingchuan commented on zh/api.md
> +传入一个句柄函数，并返回一个默认不可手动修改的 ref 对象。
这里的 getter 用的很好 👍！

2020-04-28 04:30 UTC, ShenQingchuan commented on zh/api.md
> +- 当监听回调因依赖项变化被触发时，将调用 `onTrigger`
我将这里改为了：

> - 依赖项变更导致副作用被触发时，将调用 `onTrigger`

征询您的意见。

Thanks.

2020-04-28 04:32 UTC, ShenQingchuan commented
@aomiba  很抱歉，也有些不巧，您方才在 review 时我刚好上传了一版我的 自我修正，期间结合之前 `zh/index.md` 中 @JinJang 给出的一些建议和修正的经验，wiki 的规范等信息，简化了很多冗杂、口语化的表达，想要更贴近 RFC 英语原文的表达内容。

给您 review 带来的困扰与不便感到抱歉，感谢您的付出与时间。

2020-04-28 04:39 UTC, aomiba commented on zh/api.md
> +#### 手动停止监听
qingchuan, 可否提供一个你的公开邮箱给我， 我改好了直接 mail 你，在这个线上操作不太习惯， 我的邮箱 a@aomiba.com

2020-04-28 04:51 UTC, aomiba commented
> @aomiba 很抱歉，也有些不巧，您方才在 review 时我刚好上传了一版我的 自我修正，期间结合之前 `zh/index.md` 中 @Jinjiang 给出的一些建议和修正的经验，wiki 的规范等信息，简化了很多冗杂、口语化的表达，想要更贴近 RFC 英语原文的表达内容。
> 
> 给您 review 带来的困扰与不便感到抱歉，感谢您的付出与时间。

没事儿，我们有一个共同的目标：让更多人更早的接触到 vue3

我有一个提议， 线上操作不太友好，我想直接拉你fork 的库， 然后本地调整， 本地完成后直接把那个文件发给你，你参考。我的邮箱 a@aomiba.com,如果你同意这种协助方式，可以发个邮件给我

2020-04-28 05:29 UTC, Jinjiang commented
callback 这个词我们之前统一翻译成了“回调”，如果有拿不准的词，其中一个建议是可以参考 vue 其它已有的文档中对于这个词的译法。

2020-05-06 06:06 UTC, ShenQingchuan commented
@Jinjiang  我已经接受了 @aomiba 推送的 PR，完成了 `zh/api.md` 的 review。
向您提出 PR 合并请求。

2020-05-06 06:55 UTC, Jinjiang commented
@ShenQingchuan 好，谢谢。 我会最后做一次 final review。

2020-05-06 07:01 UTC, Jinjiang approved these changes

2020-05-06 07:02 UTC, Jinjiang commented
@yyx990803 I think this PR is ready to be merged. Thanks.

2020-05-11 03:33 UTC, ShenQingchuan commented
@yyx990803  @Jinjiang 
Has this PR still work on progress or been outdated ?

2020-05-12 00:20 UTC, merged